spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards
    username: user
    password: secret
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.flashcards: DEBUG
    org.springframework.web: DEBUG