-- PostgreSQL Script für Flashcards App
-- Version 3: Vollständig mit 230 Fragen und zufälliger Antwortreihenfolge

-- Cleanup (falls Tabellen bereits existieren)
DROP TABLE IF EXISTS flashcard_set_mapping CASCADE;
DROP TABLE IF EXISTS flashcard_options CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS flashcard_sets CASCADE;

-- Erstelle flashcard_sets Tabelle
CREATE TABLE IF NOT EXISTS flashcard_sets
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(2000) NOT NULL
);

-- Erstelle cards Tabelle
CREATE TABLE IF NOT EXISTS cards
(
    id       BIGSERIAL PRIMARY KEY,
    question VARCHAR(1000) NOT NULL,
    answer   VARCHAR(4000) NOT NULL,
    type     VARCHAR(32)   NOT NULL
);

-- Erstelle flashcard_options Tabelle
CREATE TABLE IF NOT EXISTS flashcard_options
(
    id           BIGSERIAL PRIMARY KEY,
    option_text  VARCHAR(2000) NOT NULL,
    is_correct   BOOLEAN       NOT NULL DEFAULT false,
    flashcard_id BIGINT        NOT NULL,
    FOREIGN KEY (flashcard_id) REFERENCES cards (id) ON DELETE CASCADE
);

-- Erstelle flashcard_set_mapping Tabelle
CREATE TABLE IF NOT EXISTS flashcard_set_mapping
(
    flashcard_id BIGINT NOT NULL,
    set_id       BIGINT NOT NULL,
    PRIMARY KEY (flashcard_id, set_id),
    FOREIGN KEY (flashcard_id) REFERENCES cards (id) ON DELETE CASCADE,
    FOREIGN KEY (set_id) REFERENCES flashcard_sets (id) ON DELETE CASCADE
);

-- Seeding: Flashcard Sets
INSERT INTO flashcard_sets (id, name, description)
VALUES (1, 'Undefined', 'Standard-Set für nicht zugeordnete Karten'),
       (2, 'Alle Fragen', 'Sammel-Set mit allen verfügbaren Fragen'),
       (23, 'Planen, Vorbereiten und Durchführen', 'Fragen zur Projektplanung und -durchführung'),
       (24, 'Informieren und Beraten von Kunden', 'Fragen zur Kundenkommunikation und -beratung'),
       (25, 'Marktgängige IT-Systeme und Lösungen', 'Fragen zu aktuellen IT-Systemen und Technologien'),
       (26, 'Entwickeln, Erstellen und Betreuen', 'Fragen zur Software- und Systementwicklung'),
       (27, 'Qualitätssichernde Maßnahmen', 'Fragen zum Qualitätsmanagement'),
       (28, 'IT-Sicherheit, Datenschutz und Ergonomie', 'Fragen zu Sicherheit, Datenschutz und Arbeitsplatzgestaltung'),
       (29, 'Auftragsabschluss und Leistungserbringung', 'Fragen zum Projektabschluss und Service');

-- Reset sequence for flashcard_sets
SELECT setval('flashcard_sets_id_seq', (SELECT MAX(id) FROM flashcard_sets));

-- =====================
-- Seeding: 230 Flashcards
-- =====================

INSERT INTO cards (id, question, answer, type) VALUES
(1, 'Was versteht man unter dem Begriff IT-Benchmarking?', 'Ein systematischer Vergleich von IT-Leistungen mit anderen Unternehmen.', 'TEXT'),
(2, 'Welche Kriterien müssen erfüllt sein für ein Marktgleichgewicht?', 'Angebot und Nachfrage sind gleich.', 'SINGLE_CHOICE'),
(3, 'Wann spricht man von einem Käufermarkt?', 'Das Angebot übersteigt die Nachfrage.', 'SINGLE_CHOICE'),
(4, 'Welche Aufgaben und Ziele verfolgen die betrieblichen Grundfunktionen?', 'Beschaffung, Produktion, Absatz, Finanzierung.', 'TEXT'),
(5, 'Welche Merkmale besitzt eine Europäische Gesellschaft (SE)? (Mehrere Antworten sind richtig)', 'Mindestkapital 120.000€, Sitz in EU, grenzüberschreitender Charakter.', 'MULTIPLE_CHOICE'),
(6, 'Welche Kriterien müssen für die Marktform des Polypols erfüllt sein?', 'Viele Anbieter, viele Nachfrager.', 'SINGLE_CHOICE'),
(7, 'Welche Unternehmensformen sind in Deutschland Personengesellschaften? (Mehrere Antworten sind richtig)', 'GbR, OHG, KG.', 'MULTIPLE_CHOICE'),
(8, 'Welche Bedingungen und welche Haftungsregeln gelten bei einer offenen Handelsgesellschaft - OHG?', 'Unbeschränkte, unmittelbare, solidarische Haftung.', 'TEXT'),
(9, 'Welche Sachverhalte können das Betriebsergebnis positiv beeinflussen? (Mehrere Antworten sind richtig)', 'Umsatzsteigerung, Kostensenkung, Effizienzsteigerung.', 'MULTIPLE_CHOICE'),
(10, 'Welchem Zweck dienen Kundenbefragungen im Marketing?', 'Ermittlung von Kundenwünschen und -zufriedenheit.', 'SINGLE_CHOICE'),
(11, 'Unterscheide bitte geschlossene und offene Fragen.', 'Geschlossene Fragen erlauben nur bestimmte Antworten (z.B. Ja/Nein), offene Fragen lassen beliebige Antworten zu.', 'TEXT'),
(12, 'Wozu dient eine ABC-Analyse im Controlling?', 'Zur Priorisierung von Objekten nach ihrer relativen Wichtigkeit (Wert/Menge).', 'SINGLE_CHOICE'),
(13, 'Was versteht man unter dem Begriff Cross-Selling?', 'Verkauf von ergänzenden Produkten an Bestandskunden.', 'TEXT'),
(14, 'Was ist die Appell-Ebene der Aussage "Sie müssen pünktlich liefern!" nach dem Vier-Ohren-Modell?', 'Die Aufforderung, die Lieferung pünktlich zu erbringen.', 'SINGLE_CHOICE'),
(15, 'Welche Regeln sollte man im telefonischen Kundensupport beachten? (Mehrere Antworten sind richtig)', 'Aktiv zuhören, Freundlich bleiben, Kompetent auftreten.', 'MULTIPLE_CHOICE'),
(16, 'Beschreibe den Begriff Pre-Sales-Angebot und nenne 3 Beispiele.', 'Aktivitäten vor dem Verkauf. Bsp: Bedarfsanalyse, Produktpräsentation, Teststellung.', 'TEXT'),
(17, 'Welche Vor- und Nachteile bieten Webinare?', 'Vorteil: Ortsunabhängig. Nachteil: Weniger interaktiv.', 'SINGLE_CHOICE'),
(18, 'Nenne die englischen Bezeichnungen der Schichten 1, 2 und 7 im OSI-Modell.', 'Physical, Data Link, Application.', 'TEXT'),
(19, 'Was ist eine Nutzwertanalyse?', 'Eine Methode zur Bewertung von Alternativen anhand von gewichteten Kriterien.', 'SINGLE_CHOICE'),
(20, 'Nenne Vor- und Nachteile eines direkten Vertriebs.', 'Vorteil: Direkter Kundenkontakt. Nachteil: Hoher Aufwand.', 'TEXT'),
(21, 'Mit welchen Maßnahmen kann man die Kundenzufriedenheit erhöhen? (Mehrere Antworten sind richtig)', 'Guter Service, Hohe Produktqualität, Schnelle Reaktion.', 'MULTIPLE_CHOICE'),
(22, 'Welchem Zweck dient ein Angebotsvergleich?', 'Auswahl des wirtschaftlichsten Angebots.', 'SINGLE_CHOICE'),
(23, 'Was ist bei der Außerbetriebnahme von IT-Systemen zu beachten?', 'Datensicherung, sichere Datenlöschung, umweltgerechte Entsorgung.', 'TEXT'),
(24, 'Worin besteht der Unterschied zwischen Hypervisor Typ 1 und Typ 2?', 'Typ 1 (bare-metal) läuft direkt auf Hardware, Typ 2 auf einem Host-Betriebssystem.', 'SINGLE_CHOICE'),
(25, 'Welche Funktionen bietet eine Dockingstation für Notebooks?', 'Anschluss von Peripherie, Stromversorgung, Netzwerk.', 'TEXT'),
(26, 'Welche Video-Schnittstellen sind für 4K und 8K Auflösung geeignet? (Mehrere Antworten sind richtig)', 'HDMI 2.1, DisplayPort 1.4.', 'MULTIPLE_CHOICE'),
(27, 'Welche technischen Merkmale hat ein Notebook?', 'Kompakt, mobil, integrierter Akku/Display/Tastatur.', 'SINGLE_CHOICE'),
(28, 'Erläutern Sie den Begriff „Logische Prozessoren“.', 'Anzahl der Threads, die eine CPU parallel bearbeiten kann (z.B. via Hyper-Threading).', 'TEXT'),
(29, 'Welchen Vorteil bringt der Einsatz von Dual-Channel-Technik bei Speichermodulen?', 'Erhöhung der Speicherbandbreite.', 'SINGLE_CHOICE'),
(30, 'Was verbirgt sich hinter Bezeichnung UHD 4K?', 'Eine Auflösung von 3840 x 2160 Pixeln.', 'TEXT'),
(31, 'Was versteht man unter einem Thin-Client?', 'Ein Endgerät mit minimaler Hardware, das auf Server-Ressourcen zugreift.', 'SINGLE_CHOICE'),
(32, 'Welche IT-Komponenten sind reine Eingabegeräte? (Mehrere Antworten sind richtig)', 'Scanner, Maus, Tastatur.', 'MULTIPLE_CHOICE'),
(33, 'Nenne Vorteile des USB-C Anschlusses.', 'Verdrehsicher, höhere Datenraten, Power Delivery.', 'TEXT'),
(34, 'Nenne die verschiedenen Cloud-Formen.', 'Public, Private, Hybrid, Multi Cloud.', 'SINGLE_CHOICE'),
(35, 'Was versteht man unter dem Begriff Green-IT?', 'Nachhaltiger und ressourcenschonender Einsatz von IT.', 'TEXT'),
(36, 'Erkläre das Servicemodell Infrastructure as a Service (IaaS).', 'Bereitstellung von virtualisierter IT-Infrastruktur (Rechenleistung, Speicher).', 'SINGLE_CHOICE'),
(37, 'Nenne Vorteile des Servicemodells PaaS (Platform as a Service). (Mehrere Antworten sind richtig)', 'Schnellere Entwicklung, Geringerer administrativer Aufwand, Skalierbarkeit.', 'MULTIPLE_CHOICE'),
(38, 'Erkläre den Cloud Computing Begriff Software as a Service (SaaS).', 'Bereitstellung von Software-Anwendungen über das Internet.', 'TEXT'),
(39, 'Was ist ein Host-Bus-Adapter (HBA)?', 'Eine Karte, die einen Host mit einem Storage-Netzwerk (z.B. FC) verbindet.', 'SINGLE_CHOICE'),
(40, 'Nenne die 3 USV-Klassen nach IEC 62040-3.', 'VFD (Offline), VI (Line-Interactive), VFI (Online).', 'TEXT'),
(41, 'Welche Aufgabe übernimmt eine USV?', 'Sicherstellung der Stromversorgung bei Netzausfall.', 'SINGLE_CHOICE'),
(42, 'Welche Aufgabe übernimmt ein Datenbankmanagementsystem (DBMS)?', 'Verwaltung, Speicherung und Abruf von Daten.', 'TEXT'),
(43, 'Was ist eine DMZ (Demilitarisierte Zone)?', 'Ein geschütztes Netzwerksegment zwischen internem Netz und Internet.', 'SINGLE_CHOICE'),
(44, 'Welche Aufgabe hat ein Netzwerk-Router?', 'Kopplung von Netzwerken und Weiterleitung von Datenpaketen.', 'TEXT'),
(45, 'Welche Aufgabe hat die Transportschicht (Layer 4) im OSI-Modell?', 'Segmentierung der Daten und Flusskontrolle.', 'SINGLE_CHOICE'),
(46, 'Was ist eine Broadcast-Domäne?', 'Ein Netzwerkbereich, in dem ein Broadcast alle Geräte erreicht.', 'TEXT'),
(47, 'Was ist ein Network Attached Storage (NAS)?', 'Ein an das Netzwerk angebundener Dateispeicher.', 'SINGLE_CHOICE'),
(48, 'Was ist ein Storage Area Network (SAN)?', 'Ein dediziertes Netzwerk für blockbasierten Speicherzugriff.', 'TEXT'),
(49, 'Ein Netz (192.168.30.0/24) soll in 8 Subnetze unterteilt werden. Wie lautet die Subnetzmaske?', '255.255.255.224', 'SINGLE_CHOICE'),
(50, 'Was bedeutet in der Netzwerktechnologie der Begriff PoE?', 'Power over Ethernet', 'TEXT'),
(51, 'Wie lautet die typische Notation einer iSCSI-Verbindung?', 'iqn (iSCSI Qualified Name).', 'SINGLE_CHOICE'),
(52, 'Wie wird eine Fibre Channel Verbindung adressiert?', 'World Wide Name (WWN).', 'TEXT'),
(53, 'Erläutere den Begriff Unicast.', '1-zu-1-Kommunikation zwischen einem Sender und einem Empfänger.', 'SINGLE_CHOICE'),
(54, 'Was versteht man unter dem Begriff Multicast?', '1-zu-N-Kommunikation an eine Gruppe von Empfängern.', 'TEXT'),
(55, 'Erläutere den Begriff Broadcast.', '1-zu-Alle-Kommunikation in einem Netzwerksegment.', 'SINGLE_CHOICE'),
(56, 'Welche Aufgabe hat bei IPv4 eine Broadcast-Adresse?', 'Adressierung aller Hosts in einem Subnetz.', 'TEXT'),
(57, 'Beschreibe die Bestandteile einer IPv6-Adresse.', '128 Bit, hexadezimal, unterteilt in Netzwerkpräfix und Interface-ID.', 'SINGLE_CHOICE'),
(58, 'Kürze die IPv6 Adresse 2003:00dc:075a:dd00:e130:c353:3188:afb6.', '2003:dc:75a:dd00:e130:c353:3188:afb6', 'TEXT'),
(59, 'Benenne die gängigsten IPv6-Adresstypen. (Mehrere Antworten sind richtig)', 'Global Unicast, Link-Local, Multicast.', 'MULTIPLE_CHOICE'),
(60, 'Was versteht man bei IPv6 unter Stateless Address Autoconfiguration (SLAAC)?', 'Automatische Adresskonfiguration ohne DHCP-Server.', 'SINGLE_CHOICE'),
(61, 'Worin unterscheiden sich Single- und Multimodefasern?', 'Kerndurchmesser, Lichtquelle, Reichweite, Kosten.', 'TEXT'),
(62, 'Nenne Vor- und Nachteile von Singlemode-Glasfasern.', 'Vorteil: Große Reichweite. Nachteil: Teure Hardware.', 'SINGLE_CHOICE'),
(63, 'Nenne Vor- und Nachteile von Multimodefasern.', 'Vorteil: Günstigere Hardware. Nachteil: Begrenzte Reichweite.', 'TEXT'),
(64, 'Welche Aufgabe hat das Simple Network Management Protocol (SNMP)?', 'Überwachung und Steuerung von Netzwerkgeräten.', 'SINGLE_CHOICE'),
(65, 'Welche Aufgaben hat ein DHCP-Server?', 'Automatische Zuweisung von IP-Adressen und Netzwerkkonfiguration.', 'TEXT'),
(66, 'Welche Informationen stellt der DHCP-Dienst zur Verfügung? (Mehrere Antworten sind richtig)', 'IP-Adresse, Subnetzmaske, Gateway, DNS-Server.', 'MULTIPLE_CHOICE'),
(67, 'Vergleiche die Protokolle UDP und TCP.', 'TCP: verbindungsorientiert, zuverlässig. UDP: verbindungslos, schnell.', 'SINGLE_CHOICE'),
(68, 'Welche verkürzte Schreibweise der IPv6-Adresse 2001:0db8:0f3c:00d7:7dab:03d0:0000:00ff ist erlaubt?', '2001:db8:f3c:d7:7dab:3d0:0:ff', 'TEXT'),
(69, 'Was versteht man unter Quality of Service (QoS)?', 'Priorisierung von Datenverkehr zur Sicherstellung einer Dienstgüte.', 'SINGLE_CHOICE'),
(70, 'Wann kommt ein tagged VLAN zum Einsatz?', 'Wenn Datenverkehr mehrerer VLANs über einen Port (Trunk) läuft.', 'TEXT'),
(71, 'Beschreibe typische Merkmale des Client-Server-Modells. (Mehrere Antworten sind richtig)', 'Zentraler Server, anfragende Clients, klare Rollenverteilung.', 'MULTIPLE_CHOICE'),
(72, 'Welche Aufgabe hat ein Domain Name System (DNS)?', 'Namensauflösung von Hostnamen zu IP-Adressen.', 'SINGLE_CHOICE'),
(73, 'Unterscheide die Mailingprotokolle IMAP, SMTP sowie POP3.', 'SMTP: Versand. IMAP/POP3: Empfang.', 'TEXT'),
(74, 'Erläutere den Unterschied zwischen einem Switch und einem Router.', 'Switch: Layer 2 (MAC), verbindet Geräte im LAN. Router: Layer 3 (IP), verbindet Netzwerke.', 'SINGLE_CHOICE'),
(75, 'Was bedeutet der Begriff Standby- oder Offline-USV?', 'Die USV wird nur bei einem Stromausfall aktiv (VFD).', 'TEXT'),
(76, 'Was versteht man unter einer Online-USV?', 'Die Geräte werden permanent über den Akku versorgt (VFI).', 'SINGLE_CHOICE'),
(77, 'Was versteht man unter einer Netzinteraktiven USV?', 'Gleicht Spannungsschwankungen aus, ohne auf Akku umzuschalten (VI).', 'TEXT'),
(78, 'Was bedeutet der Begriff SSID (Service Set Identifier)?', 'Der Name eines WLAN-Netzwerks.', 'SINGLE_CHOICE'),
(79, 'Wofür stehen die Abkürzungen CMS, ERP und CRM?', 'Content Management System, Enterprise Resource Planning, Customer Relationship Management.', 'TEXT'),
(80, 'Welche Maßnahmen verbessern die PC-Geschwindigkeit? (Mehrere Antworten sind richtig)', 'Mehr RAM, schnellere CPU, Einbau einer SSD.', 'MULTIPLE_CHOICE'),
(81, 'Ermittle Vor- und Nachteile einer M.2-SSD.', 'Vorteil: Sehr schnell, kompakt. Nachteil: Teurer, wird wärmer.', 'SINGLE_CHOICE'),
(82, 'Nenne Vor- und Nachteile einer SATA-SSD.', 'Vorteil: Günstiger, kompatibel. Nachteil: Langsamer als NVMe.', 'TEXT'),
(83, 'Erläutere den Begriff des CPU-Caches.', 'Kleiner, schneller Pufferspeicher direkt auf der CPU.', 'SINGLE_CHOICE'),
(84, 'Welche Aufgabe hat die Wärmeleitpaste zwischen CPU und Kühler?', 'Verbesserung der Wärmeübertragung.', 'TEXT'),
(85, 'Berechne die Gesamtleistungsaufnahme für 10 Server (je 800W) und 25 PCs (je 350W).', '16750 Watt oder 16,75 kW.', 'TEXT'),
(86, 'Wie berechnet man die Wirkleistung von elektrischen Geräten?', 'P = U * I * cos(phi)', 'SINGLE_CHOICE'),
(87, 'Berechne die maximale Leistungsaufnahme an einer Steckdose (16A, 230V).', '3680 Watt oder 3,68 kW.', 'TEXT'),
(88, 'Eine USV (12V/4,5Ah x20) versorgt 1,2kW. Wie viel kürzer ist die Laufzeit bei 400W Zusatzlast?', 'Die Berechnung ist komplex und von vielen Faktoren abhängig.', 'SINGLE_CHOICE'),
(89, 'Nenne 3 Maßnahmen zur Verbesserung der WLAN-Empfangsqualität.', 'Repeater einsetzen, Access Point anders positionieren, Störquellen entfernen.', 'TEXT'),
(90, 'Was bedeutet es, wenn ein WLAN Access Point im Infrastructure Modus arbeitet?', 'Er ist mit einem kabelgebundenen Netzwerk verbunden und dient als zentrale Brücke.', 'SINGLE_CHOICE'),
(91, 'Was bedeutet der Begriff MIMO in der Nachrichtentechnik?', 'Multiple-Input Multiple-Output (Mehrere Antennen für Senden/Empfangen).', 'TEXT'),
(92, 'Ermittle die jährlichen Energiekosten für 2 Server (je 500W) bei 30ct/kWh.', '2628 EUR.', 'SINGLE_CHOICE'),
(93, 'Was versteht man unter Multi SSID?', 'Ein Access Point kann mehrere, voneinander getrennte WLAN-Netze (SSIDs) aufspannen.', 'TEXT'),
(94, 'Nenne Vor- und Nachteile von 2.4 GHz und 5 GHz WLAN. (Mehrere Antworten sind richtig)', '2.4GHz: höhere Reichweite, mehr Störungen. 5GHz: höhere Geschwindigkeit, geringere Reichweite.', 'MULTIPLE_CHOICE'),
(95, 'Welche Spezifikationen hat Bluetooth in Bezug auf Reichweite und Datenrate?', 'Abhängig von Klasse/Version, z.B. Klasse 2: ~10m, v5.0: bis zu 2 Mbit/s.', 'SINGLE_CHOICE'),
(96, 'Nenne Vorteile der Virtualisierung von Servern.', 'Bessere Hardware-Auslastung, einfachere Administration, Energieeinsparung.', 'TEXT'),
(97, 'Was bedeutet der Begriff Serverkonsolidierung?', 'Reduzierung der Anzahl physischer Server durch Virtualisierung.', 'SINGLE_CHOICE'),
(98, 'Welche Arten von Anforderungen gibt es an Software? (Mehrere Antworten sind richtig)', 'Funktionale Anforderungen, Nicht-funktionale Anforderungen.', 'MULTIPLE_CHOICE'),
(99, 'Welche Kosten entstehen für ein Rechenzentrum (on-Premises)?', 'Anschaffung (Hardware), Betrieb (Strom, Kühlung), Personal, Wartung.', 'TEXT'),
(100, 'Vergleiche Leasing, Kauf und Pay-per-use für Server.', 'Kauf: Eigentum, hohe Anfangskosten. Leasing: Feste Raten. Pay-per-use: Flexible, nutzungsabhängige Kosten.', 'SINGLE_CHOICE'),
(101, 'Aus welchen Bestandteilen besteht eine Handelskalkulation?', 'Bezugskalkulation, Selbstkostenkalkulation, Verkaufskalkulation.', 'TEXT'),
(102, 'Was versteht man unter dem Begriff der Bedarfsanalyse?', 'Systematische Ermittlung der Anforderungen und Bedürfnisse des Kunden.', 'SINGLE_CHOICE'),
(103, 'Nenne die Vorteile einer Bedarfsanalyse.', 'Vermeidung von Fehlentwicklungen, höhere Kundenzufriedenheit, solide Planungsgrundlage.', 'TEXT'),
(104, 'Vergleiche BIOS mit UEFI.', 'UEFI ist der Nachfolger von BIOS, bietet grafische Oberfläche, Secure Boot und unterstützt größere Festplatten.', 'SINGLE_CHOICE'),
(105, 'Beschreibe die Funktionsweise einer Remote Desktop Verbindung.', 'Die Bildschirmausgabe eines entfernten Computers wird auf dem lokalen Client angezeigt und Eingaben werden übertragen.', 'TEXT'),
(106, 'Wie kann ich mit Kommandozeilen-Werkzeugen die Namensauflösung überprüfen?', 'nslookup, ping.', 'SINGLE_CHOICE'),
(107, 'Welche Features verhindern das Laden von Schadsoftware beim Windows-Start? (Mehrere Antworten sind richtig)', 'Secure Boot, Trusted Boot, Early Launch Anti-Malware (ELAM).', 'MULTIPLE_CHOICE'),
(108, 'Erläutere den Unterschied zwischen Partitionierung und Formatierung.', 'Partitionierung teilt einen Datenträger in Bereiche. Formatierung erstellt ein Dateisystem in einer Partition.', 'TEXT'),
(109, 'Was versteht man unter einem Service-Tag oder Asset-Tag?', 'Eine eindeutige Kennzeichnung zur Identifizierung von Hardware.', 'SINGLE_CHOICE'),
(110, 'Welche Vorteile bringt der Einsatz von Thin-Clients?', 'Zentrale Verwaltung, geringere Kosten, höhere Sicherheit.', 'TEXT'),
(111, 'Was versteht man unter einem Pflichtenheft?', 'Beschreibt, wie der Auftragnehmer die Anforderungen des Lastenhefts umsetzen wird.', 'SINGLE_CHOICE'),
(112, 'Erläutere die Vor- und Nachteile beim Lizenzmodell Pay-per-use.', 'Vorteil: Flexibel, Kosten nach Nutzung. Nachteil: Schlecht kalkulierbar.', 'TEXT'),
(113, 'Was wird in einem Lastenheft beschrieben?', 'Die Gesamtheit der Anforderungen des Auftraggebers an ein Projekt oder Produkt.', 'SINGLE_CHOICE'),
(114, 'Was versteht man unter einem Convertible?', 'Ein Notebook, das sich auch als Tablet nutzen lässt (z.B. durch umklappbares Display).', 'TEXT'),
(115, 'Nenne einige Vor- und Nachteile von Tablets. (Mehrere Antworten sind richtig)', 'Vorteil: Sehr mobil, intuitive Bedienung. Nachteil: Weniger Leistung, keine physische Tastatur.', 'MULTIPLE_CHOICE'),
(116, 'Welche Vor- und Nachteile hat ein Notebook?', 'Vorteil: Mobil und leistungsstark. Nachteil: Begrenzte Aufrüstbarkeit, teurer als Desktop.', 'SINGLE_CHOICE'),
(117, 'Welche Anforderungen werden an einen Dateiserver gestellt?', 'Hohe Speicherkapazität, Verfügbarkeit, Datensicherheit, schnelle Netzwerkverbindung.', 'TEXT'),
(118, 'Erläutere die Unterschiede zwischen ADSL, VDSL und SDSL.', 'ADSL/VDSL: asymmetrisch (Download > Upload). SDSL: symmetrisch.', 'SINGLE_CHOICE'),
(119, 'Berechne die Zeit für den Download einer 2 GiB großen Datei über eine 50 Mbit/s Verbindung.', 'ca. 5 Minuten 44 Sekunden.', 'TEXT'),
(120, 'Worauf sollte man bei der Beschaffung von IT-Hardware achten?', 'Anforderungen, Kompatibilität, Kosten, Garantie, Service.', 'SINGLE_CHOICE'),
(121, 'Was versteht man unter Standardsoftware?', 'Software, die für einen breiten Markt und nicht für einen speziellen Kunden entwickelt wurde.', 'TEXT'),
(122, 'Was versteht man unter Individualsoftware?', 'Software, die speziell für die Anforderungen eines einzelnen Kunden entwickelt wird.', 'SINGLE_CHOICE'),
(123, 'Was versteht man in der Anwendungsentwicklung unter dem Begriff IDE?', 'Integrated Development Environment (Integrierte Entwicklungsumgebung).', 'TEXT'),
(124, 'Was bedeutet der Begriff „Proprietäre Software“?', 'Software, deren Nutzung, Weitergabe und Veränderung rechtlich eingeschränkt ist.', 'SINGLE_CHOICE'),
(125, 'Nenne 3 charakteristische Eigenschaften von Open Source Software. (Mehrere Antworten sind richtig)', 'Quellcode ist öffentlich, darf verändert und weitergegeben werden.', 'MULTIPLE_CHOICE'),
(126, 'Was ist unter den Begriffen OEM-Software und OEM-Hardware zu verstehen?', 'Software/Hardware, die für den Verkauf zusammen mit einem anderen Produkt (z.B. PC) bestimmt ist.', 'TEXT'),
(127, 'Was versteht man bei Rechenzentrumsbetrieb unter Skalierbarkeit?', 'Die Fähigkeit eines Systems, mit wachsender Anforderung (Last) zu wachsen.', 'SINGLE_CHOICE'),
(128, 'Was beschreibt eine EULA (End User License Agreement)?', 'Den Lizenzvertrag zwischen Softwarehersteller und Endbenutzer.', 'TEXT'),
(129, 'Beschreibe das Modell Pay-per-use in der IT.', 'Bezahlung von Diensten basierend auf der tatsächlichen Nutzung.', 'SINGLE_CHOICE'),
(130, 'Mit welchen Maßnahmen kann eine WLAN-Verbindung abgesichert werden? (Mehrere Antworten sind richtig)', 'WPA2/WPA3-Verschlüsselung, sicheres Passwort, SSID nicht broadcasten, MAC-Filter.', 'MULTIPLE_CHOICE'),
(131, 'Welche 3 VPN Verbindungsarten gibt es?', 'Site-to-Site, End-to-Site (Remote Access), End-to-End.', 'TEXT'),
(132, 'Welche Merkmale hat ein Virtual Private Network (VPN)?', 'Sicherer, verschlüsselter Tunnel durch ein unsicheres Netzwerk (z.B. Internet).', 'SINGLE_CHOICE'),
(133, 'Welche Sicherheitsmethoden und Verschlüsselungsstandards können bei WLAN zum Einsatz kommen?', 'WPA2, WPA3 mit AES-Verschlüsselung.', 'TEXT'),
(134, 'Welche Vorteile ergeben sich durch den Einsatz eines Virtual Local Area Networks (VLAN)?', 'Logische Segmentierung des Netzwerks, höhere Sicherheit, besseres Management.', 'SINGLE_CHOICE'),
(135, 'Welche Aufgabe erfüllt das Befehlszeilenkommando ARP?', 'Anzeige und Bearbeitung des ARP-Caches (Zuordnung IP- zu MAC-Adresse).', 'TEXT'),
(136, 'Beschreibe die Aufgabe des Befehls chmod in einem Linux-Betriebssystem.', 'Änderung der Dateiberechtigungen (Lesen, Schreiben, Ausführen).', 'SINGLE_CHOICE'),
(137, 'Was bedeutet S.M.A.R.T. bei Festplatten?', 'Self-Monitoring, Analysis and Reporting Technology (System zur Selbstüberwachung).', 'TEXT'),
(138, 'Bringe die Schritte zur Windows-Installation in die richtige Reihenfolge. (Mehrere Antworten sind richtig)', 'P.O.S.T. -> Bootreihenfolge festlegen -> EULA akzeptieren -> Partitionieren/Formatieren -> Benutzer anlegen.', 'MULTIPLE_CHOICE'),
(139, 'Welche Kommandos zeigen unter Linux eine IPv4-Adresse an?', 'ip addr, ifconfig.', 'SINGLE_CHOICE'),
(140, 'Wie lautet das netsh-Kommando zum Einrichten einer IPv4-Adresse?', 'netsh interface ipv4 set address name="LAN-Verbindung" static 192.168.0.1 255.255.255.0 192.168.0.254', 'TEXT'),
(141, 'Welche Bedingungen müssen beim Einsatz von Arbeitsspeichern im Dual Channel Mode erfüllt sein?', 'Zwei identische oder sehr ähnliche RAM-Module in den richtigen Slots.', 'SINGLE_CHOICE'),
(142, 'Was bedeutet der Begriff UML?', 'Unified Modeling Language.', 'TEXT'),
(143, 'Nenne einige UML-Verhaltensdiagramme. (Mehrere Antworten sind richtig)', 'Anwendungsfalldiagramm, Sequenzdiagramm, Aktivitätsdiagramm.', 'MULTIPLE_CHOICE'),
(144, 'Erkläre den Unterschied zwischen einem Objekt und einer Klasse.', 'Eine Klasse ist ein Bauplan, ein Objekt ist eine konkrete Instanz dieses Bauplans.', 'SINGLE_CHOICE'),
(145, 'Welche allgemeinen Anforderungen werden an ein Datenbanksystem gestellt?', 'Datenpersistenz, Datenintegrität, Datensicherheit, Mehrbenutzerzugriff.', 'TEXT'),
(146, 'Nenne die ersten drei Normalformen und deren Zweck.', '1NF: Atomare Werte. 2NF: Keine partiellen Abhängigkeiten. 3NF: Keine transitiven Abhängigkeiten.', 'SINGLE_CHOICE'),
(147, 'Nenne je einen SQL-Befehl für DDL, DML und DQL.', 'DDL: CREATE TABLE, DML: INSERT, DQL: SELECT.', 'TEXT'),
(148, 'Was bedeutet eine ISO 9001 Zertifizierung für einen Betrieb?', 'Der Betrieb hat ein zertifiziertes Qualitätsmanagementsystem.', 'SINGLE_CHOICE'),
(149, 'Beschreibe den PDCA-Zyklus.', 'Plan-Do-Check-Act: Ein Zyklus zur kontinuierlichen Verbesserung.', 'TEXT'),
(150, 'Was bedeutet das Label „Energy Star“?', 'Ein Label für besonders energieeffiziente Geräte.', 'SINGLE_CHOICE'),
(151, 'Was versteht man unter einem Audit im Qualitätsmanagement?', 'Eine systematische Untersuchung, ob Prozesse und Ergebnisse den Anforderungen entsprechen.', 'TEXT'),
(152, 'Welchen Qualitätskriterien unterliegt Software? (Mehrere Antworten sind richtig)', 'Funktionalität, Zuverlässigkeit, Benutzbarkeit, Effizienz, Wartbarkeit, Portabilität.', 'MULTIPLE_CHOICE'),
(153, 'Was bedeutet das Gütesiegel „Geprüfte Sicherheit“ (GS-Zeichen)?', 'Das Produkt erfüllt die deutschen Sicherheitsanforderungen.', 'SINGLE_CHOICE'),
(154, 'Was steckt hinter dem Zeichen „Blauer Engel“?', 'Ein Umweltzeichen für besonders umweltschonende Produkte und Dienstleistungen.', 'TEXT'),
(155, 'Was sollte beim Recyceln von IT-Produkten beachtet werden?', 'Fachgerechte Entsorgung gemäß Elektroschrottverordnung, Datensicherheit.', 'SINGLE_CHOICE'),
(156, 'Was sollte man beim Verschrotten von Datenträgern unbedingt beachten?', 'Sichere und irreversible Datenlöschung.', 'TEXT'),
(157, 'Was bedeutet der Begriff MFA (Multi-Factor-Authentication)?', 'Authentifizierung durch die Kombination mehrerer unabhängiger Faktoren.', 'SINGLE_CHOICE'),
(158, 'Beschreibe den Begriff Datensicherheit und nenne deren Schutzziele.', 'Schutz von Daten. Schutzziele: Vertraulichkeit, Integrität, Verfügbarkeit.', 'TEXT'),
(159, 'Worin unterscheiden sich Datensicherheit und Datenschutz?', 'Datensicherheit: Schutz der Daten (technisch). Datenschutz: Schutz personenbezogener Daten (rechtlich).', 'SINGLE_CHOICE'),
(160, 'Was versteht man im Datenschutz unter technisch-organisatorischen Maßnahmen (TOM)?', 'Konkrete Maßnahmen zur Umsetzung der Datensicherheit.', 'TEXT'),
(161, 'Durch welche Maßnahmen können TOM umgesetzt werden? (Mehrere Antworten sind richtig)', 'Zutrittskontrolle, Zugangskontrolle, Zugriffskontrolle, Verschlüsselung.', 'MULTIPLE_CHOICE'),
(162, 'Nenne Vorteile einer ISO/IEC 27001 Zertifizierung.', 'Nachweis eines hohen IT-Sicherheitsniveaus, Vertrauensbildung, Risikominimierung.', 'SINGLE_CHOICE'),
(163, 'Welches sind die Ziele bei der Datenminimierung?', 'Nur so viele personenbezogene Daten wie für den Zweck nötig erheben und verarbeiten.', 'TEXT'),
(164, 'Welche Rechte hat eine Person laut DSGVO? (Mehrere Antworten sind richtig)', 'Recht auf Auskunft, Berichtigung, Löschung, Datenübertragbarkeit.', 'MULTIPLE_CHOICE'),
(165, 'Was ist eine PKI (Public Key Infrastructure)?', 'Ein System zur Verwaltung und Nutzung von digitalen Zertifikaten.', 'SINGLE_CHOICE'),
(166, 'Was versteht man unter einem digitalen Zertifikat?', 'Ein elektronischer Echtheitsnachweis für einen öffentlichen Schlüssel.', 'TEXT'),
(167, 'Was ist eine SPI (Stateful Packet Inspection) Firewall?', 'Eine Firewall, die den Zustand von Verbindungen verfolgt.', 'SINGLE_CHOICE'),
(168, 'Was versteht man unter dem Begriff Endpoint-Security?', 'Schutz von Endgeräten (PCs, Laptops, Smartphones).', 'TEXT'),
(169, 'Welche Anwendungen verwenden kryptografische Hashfunktionen? (Mehrere Antworten sind richtig)', 'Passwortspeicherung, Digitale Signaturen, Datenintegritätsprüfung.', 'MULTIPLE_CHOICE'),
(170, 'Nenne Einsatzbereiche und Verfahren von symmetrischen Schlüsseln.', 'Verschlüsselung großer Datenmengen. Verfahren: AES, DES.', 'SINGLE_CHOICE'),
(171, 'Erläutere den Unterschied zwischen einem differentiellen und inkrementellen Backup.', 'Differentiell: sichert Änderungen seit letztem Voll-Backup. Inkrementell: sichert Änderungen seit letztem Backup.', 'TEXT'),
(172, 'Wie gestaltet sich ein Backup-Plan nach dem Großvater-Vater-Sohn-Prinzip?', 'Tägliche (Sohn), wöchentliche (Vater) und monatliche (Großvater) Backups.', 'SINGLE_CHOICE'),
(173, 'Unterscheide die Begriffe Malware, Ransomware und Trojaner.', 'Malware: Oberbegriff. Ransomware: Erpressersoftware. Trojaner: Getarnte Schadsoftware.', 'TEXT'),
(174, 'Welchem Zweck dient das IT-Sicherheitsmanagement?', 'Planung, Steuerung und Kontrolle der IT-Sicherheit.', 'SINGLE_CHOICE'),
(175, 'Welche Kriterien muss eine sichere Passwortrichtlinie erfüllen? (Mehrere Antworten sind richtig)', 'Mindestlänge, Komplexität, Regelmäßiger Wechsel.', 'MULTIPLE_CHOICE'),
(176, 'Erläutere den Begriff Security by Design.', 'Integration von Sicherheit von Anfang an in den Entwicklungsprozess.', 'TEXT'),
(177, 'Benenne je 2 Vor- und Nachteile von WPA2-Personal und WPA2-Enterprise.', 'Personal: Einfach, aber unsicherer. Enterprise: Sicher, aber komplexer.', 'SINGLE_CHOICE'),
(178, 'Welche Sicherheitsmaßnahmen sind beim Einsatz eines E-Mail-Systems zu beachten?', 'Verschlüsselung (TLS, S/MIME), Spam-Filter, Virenscanner.', 'TEXT'),
(179, 'Welche Bedingungen muss ein ergonomischer PC-Arbeitsplatz erfüllen?', 'Richtige Tisch-/Stuhlhöhe, matter Bildschirm, gute Beleuchtung.', 'SINGLE_CHOICE'),
(180, 'Welche Aussagen trifft die Arbeitsstättenverordnung (ArbStättV) zu Bildschirm und Tastatur?', 'Bildschirm: flimmerfrei, reflexionsarm. Tastatur: neigbar, getrennt.', 'TEXT'),
(181, 'Was ist der PDCA-Zyklus und aus welchen Schritten besteht er?', 'Plan, Do, Check, Act - ein kontinuierlicher Verbesserungsprozess.', 'SINGLE_CHOICE'),
(182, 'Beschreibe die fünf Punkte der SMART-Methode.', 'Spezifisch, Messbar, Akzeptiert, Realistisch, Terminiert.', 'TEXT'),
(183, 'Welche Maßnahmen haben einen positiven Effekt auf die Arbeitsqualität? (Mehrere Antworten sind richtig)', 'Weiterbildung, gutes Arbeitsklima, ergonomische Arbeitsplätze.', 'MULTIPLE_CHOICE'),
(184, 'Mit welchen Maßnahmen kann man die Produktqualität verbessern?', 'Qualitätsmanagement, Tests, Kundenfeedback, KVP.', 'SINGLE_CHOICE'),
(185, 'Welches sind die Kriterien einer Schutzbedarfsanalyse?', 'Vertraulichkeit, Integrität, Verfügbarkeit.', 'TEXT'),
(186, 'Beschreibe die Schutzbedarfskategorien (normal, hoch, sehr hoch) lt. BSI.', 'Normal: Schaden begrenzt. Hoch: Schaden beträchtlich. Sehr hoch: Schaden existenziell.', 'SINGLE_CHOICE'),
(187, 'Welcher Schutzbedarf gilt für einen Router nach BSI IT-Grundschutz?', 'Hohe Verfügbarkeit, hohe Integrität, normale Vertraulichkeit.', 'TEXT'),
(188, 'Welche Maßnahmen sind geeignet, um die IT-Sicherheit zu erhöhen? (Mehrere Antworten sind richtig)', 'Firewall, Virenschutz, Backups, Zutrittskontrolle.', 'MULTIPLE_CHOICE'),
(189, 'Aus welchen Phasen besteht der Sicherheitsprozess laut BSI?', 'Initiierung, Konzeption, Umsetzung, Betrieb, Verbesserung.', 'SINGLE_CHOICE'),
(190, 'Welche Themen sind für einen IT-Sicherheitsbeauftragten von Bedeutung?', 'Risikomanagement, Notfallmanagement, Sensibilisierung der Mitarbeiter.', 'TEXT'),
(191, 'Welches sind die Inhalte einer Zertifizierung nach ISO 27001?', 'Anforderungen an ein Informationssicherheits-Managementsystem (ISMS).', 'SINGLE_CHOICE'),
(192, 'Was sind die Vorteile einer Zertifizierung nach ISO 27001?', 'Wettbewerbsvorteil, Vertrauensbildung, Risikobehandlung.', 'TEXT'),
(193, 'Welche Kriterien müssen erfüllt sein, um die Warenannahme zu verweigern?', 'Falsche Ware, beschädigte Ware, falsche Menge, Lieferverzug.', 'SINGLE_CHOICE'),
(194, 'Was versteht man unter einer Eskalationsstufe im IT-Support?', 'Die Weiterleitung eines Problems an eine höhere Support-Ebene.', 'TEXT'),
(195, 'Was versteht man unter einem Service Level Agreement (SLA)?', 'Ein Vertrag, der die Qualität einer IT-Dienstleistung definiert.', 'SINGLE_CHOICE'),
(196, 'Nenne die wesentlichen Bestandteile eines Kaufvertrags.', 'Vertragsparteien, Kaufgegenstand, Kaufpreis, Liefer- und Zahlungsbedingungen.', 'TEXT'),
(197, 'Erläutere das mehrstufige Prinzip des First-, Second- und Third-Level-Supports.', '1st: Annahme. 2nd: Komplexe Probleme. 3rd: Experten/Hersteller.', 'SINGLE_CHOICE'),
(198, 'Welche Vertragsbestandteile sollte ein Vertrag zur Softwareerstellung regeln? (Mehrere Antworten sind richtig)', 'Leistungsumfang, Abnahmekriterien, Nutzungsrechte, Vergütung.', 'MULTIPLE_CHOICE'),
(199, 'Welche Bestandteile hat ein IT-Servicevertrag?', 'Leistungsbeschreibung, SLAs, Laufzeit, Vergütung.', 'TEXT'),
(200, 'Mit welchen Maßnahmen kann der Umweltschutz im IT-Betrieb berücksichtigt werden?', 'Green IT: Virtualisierung, energieeffiziente Hardware, Recycling.', 'SINGLE_CHOICE'),
(201, 'Welches sind die ökonomischen Ziele eines Unternehmens?', 'Gewinnmaximierung, Umsatzsteigerung, Kostensenkung.', 'TEXT'),
(202, 'Unterscheide die 3 Cloud-Computing Begriffe IaaS, SaaS und PaaS.', 'IaaS: Infrastruktur. PaaS: Plattform. SaaS: Software.', 'SINGLE_CHOICE'),
(203, 'Was ist ein Organigramm?', 'Eine grafische Darstellung der Aufbauorganisation.', 'TEXT'),
(204, 'Was versteht man unter einer Aufbauorganisation?', 'Die hierarchische Struktur eines Unternehmens.', 'SINGLE_CHOICE'),
(205, 'Was versteht man unter einem Mehrliniensystem?', 'Ein Mitarbeiter erhält Anweisungen von mehreren Vorgesetzten.', 'TEXT'),
(206, 'Was versteht man unter einer Stabsstelle?', 'Eine beratende Einheit ohne Weisungsbefugnis.', 'SINGLE_CHOICE'),
(207, 'Wie ist eine Stablinienorganisation aufgebaut?', 'Einliniensystem, ergänzt durch Stabsstellen.', 'TEXT'),
(208, 'Was versteht man unter einer Matrixorganisation?', 'Mitarbeiter haben zwei Vorgesetzte (funktional, disziplinarisch).', 'SINGLE_CHOICE'),
(209, 'Welche Bedeutung haben die Abkürzungen i. V., i. A. sowie ppa.?', 'i.V.: in Vollmacht, i.A.: im Auftrag, ppa.: per Prokura.', 'TEXT'),
(210, 'Was versteht man unter dem Begriff Prokura?', 'Eine umfassende, gesetzlich definierte Vertretungsmacht.', 'SINGLE_CHOICE'),
(211, 'Erläutere den Begriff der doppelten Buchführung.', 'Jeder Geschäftsvorfall wird auf zwei Konten (Soll und Haben) gebucht.', 'TEXT'),
(212, 'Was versteht man unter beruflicher Fortbildung und Umschulung?', 'Fortbildung: Anpassung im Beruf. Umschulung: Erlernen eines neuen Berufs.', 'SINGLE_CHOICE'),
(213, 'Was versteht man unter einer beruflichen Weiterbildung?', 'Maßnahmen zur Erweiterung beruflicher Kenntnisse.', 'TEXT'),
(214, 'Welche Testverfahren kennst du? (Mehrere Antworten sind richtig)', 'Unit-Test, Integrationstest, Systemtest, Akzeptanztest.', 'MULTIPLE_CHOICE'),
(215, 'Was bedeuten Black-Box-Test und White-Box-Test?', 'Black-Box: Test ohne Kenntnis der Interna. White-Box: Test mit Kenntnis der Interna.', 'SINGLE_CHOICE'),
(216, 'Was versteht man unter Nachhaltigkeit in der IT-Branche?', 'Ökologische, ökonomische und soziale Verantwortung.', 'TEXT'),
(217, 'Nenne die wesentlichen Bestandteile eines Abnahmeprotokolls.', 'Projektdaten, Teilnehmer, Ergebnis, Mängel, Unterschriften.', 'SINGLE_CHOICE'),
(218, 'Welche Schritte sind nach Abschluss der Leistungserbringung notwendig?', 'Abnahme, Rechnungsstellung, Archivierung.', 'TEXT'),
(219, 'Nenne 3 Methoden zur Einweisung eines Kunden am Arbeitsplatz.', 'Persönliche Einweisung, Handbuch, Schulung.', 'SINGLE_CHOICE'),
(220, 'Welche Bedeutung hat der Begriff Blended Learning?', 'Eine Mischung aus Präsenzveranstaltungen und E-Learning.', 'TEXT'),
(221, 'Was verbirgt sich hinter dem Begriff Rollout?', 'Die geplante Einführung neuer Hard- oder Software.', 'SINGLE_CHOICE'),
(222, 'Welche Prozesse müssen bei einem Software-Rollout beachtet werden? (Mehrere Antworten sind richtig)', 'Planung, Paketierung, Pilotphase, Verteilung.', 'MULTIPLE_CHOICE'),
(223, 'Welche Dinge müssen bei einem IT-Hardware-Rollout beachtet werden?', 'Beschaffung, Konfiguration, Verteilung, Entsorgung.', 'TEXT'),
(224, 'Welche Unterscheidungsmerkmale haben Kauf, Miete und Leasing?', 'Kauf: Eigentum. Miete: Kurzfristige Nutzung. Leasing: Langfristige Nutzung.', 'SINGLE_CHOICE'),
(225, 'Welche Vor- und Nachteile hat der Kauf von IT-Hardware?', 'Vorteil: Eigentum. Nachteil: Hohe Kapitalbindung.', 'TEXT'),
(226, 'Welche Vor- und Nachteile hat das Leasing von IT-Hardware?', 'Vorteil: Aktuelle Hardware, geringe Kapitalbindung. Nachteil: Kein Eigentum, oft teurer.', 'SINGLE_CHOICE'),
(227, 'Was ist der Unterschied zwischen einer Aufbau- und einer Ablauforganisation?', 'Aufbauorganisation: Wer? (Struktur). Ablauforganisation: Wie? (Prozesse).', 'TEXT'),
(228, 'Was ist ein Gantt-Diagramm?', 'Ein Balkendiagramm zur Darstellung eines Projektzeitplans.', 'SINGLE_CHOICE'),
(229, 'Was sind die Hauptaufgaben des Projektmanagements? (Mehrere Antworten sind richtig)', 'Planung, Steuerung, Kontrolle, Abschluss von Projekten.', 'MULTIPLE_CHOICE'),
(230, 'Was versteht man unter dem "magischen Dreieck" im Projektmanagement?', 'Die Zielkonflikte zwischen Zeit, Kosten und Qualität (Leistungsumfang).', 'TEXT');

-- Optionen für SINGLE_CHOICE und MULTIPLE_CHOICE
INSERT INTO flashcard_options (flashcard_id, option_text, is_correct) VALUES
-- 2 SINGLE_CHOICE
(2, 'Der Preis ist maximal.', false),
(2, 'Der Staat reguliert die Preise.', false),
(2, 'Angebot und Nachfrage sind gleich.', true),
(2, 'Es gibt nur einen Anbieter.', false),
(2, 'Die Nachfrage übersteigt das Angebot.', false),
-- 3 SINGLE_CHOICE
(3, 'Die Nachfrage übersteigt das Angebot.', false),
(3, 'Das Angebot übersteigt die Nachfrage.', true),
(3, 'Angebot und Nachfrage sind ausgeglichen.', false),
(3, 'Es gibt nur wenige Anbieter.', false),
(3, 'Die Preise sind staatlich festgelegt.', false),
-- 5 MULTIPLE_CHOICE
(5, 'Haftung ist immer auf das Gesellschaftsvermögen beschränkt', false),
(5, 'Mindestkapital von 120.000 Euro', true),
(5, 'Sitz in einem EU-Mitgliedsstaat', true),
(5, 'Keine Mitbestimmung der Arbeitnehmer erforderlich', false),
(5, 'Grenzüberschreitender Charakter (z.B. durch Fusion)', true),
-- 6 SINGLE_CHOICE
(6, 'Ein Anbieter, viele Nachfrager.', false),
(6, 'Viele Anbieter, viele Nachfrager.', true),
(6, 'Wenige Anbieter, viele Nachfrager.', false),
(6, 'Ein Nachfrager, viele Anbieter.', false),
(6, 'Wenige Nachfrager, wenige Anbieter.', false),
-- 7 MULTIPLE_CHOICE
(7, 'Aktiengesellschaft (AG)', false),
(7, 'Gesellschaft bürgerlichen Rechts (GbR)', true),
(7, 'Offene Handelsgesellschaft (OHG)', true),
(7, 'Gesellschaft mit beschränkter Haftung (GmbH)', false),
(7, 'Kommanditgesellschaft (KG)', true),
-- 9 MULTIPLE_CHOICE
(9, 'Steigerung der Umsatzerlöse', true),
(9, 'Erhöhung der Fixkosten', false),
(9, 'Senkung der variablen Kosten', true),
(9, 'Effizienzsteigerung in der Produktion', true),
(9, 'Verringerung der Verkaufspreise ohne Mengenanpassung', false),
-- 10 SINGLE_CHOICE
(10, 'Festlegung der Verkaufspreise.', false),
(10, 'Kontrolle der Mitarbeiter.', false),
(10, 'Optimierung der Produktionsprozesse.', false),
(10, 'Ermittlung von Kundenwünschen und -zufriedenheit.', true),
(10, 'Erstellung der Bilanz.', false),
-- 12 SINGLE_CHOICE
(12, 'Ein Verfahren zur Priorisierung von Objekten nach ihrer Wichtigkeit.', true),
(12, 'Eine Methode zur Berechnung des Unternehmenswerts.', false),
(12, 'Ein Modell zur Vorhersage von Markttrends.', false),
(12, 'Eine Technik zur Analyse von Konkurrenzprodukten.', false),
(12, 'Ein Instrument zur Personalbeurteilung.', false),
-- 14 SINGLE_CHOICE
(14, 'Sachinhalt: "Die Lieferung ist nicht pünktlich."', false),
(14, 'Appell: "Sorgen Sie für Pünktlichkeit!"', true),
(14, 'Selbstoffenbarung: "Ich bin verärgert."', false),
(14, 'Beziehung: "Ich bin mit Ihnen unzufrieden."', false),
(14, 'Nonverbale Ebene: "Der Kunde verschränkt die Arme."', false),
-- 15 MULTIPLE_CHOICE
(15, 'Den Kunden unterbrechen, um Zeit zu sparen.', false),
(15, 'Aktiv zuhören und den Kunden ausreden lassen.', true),
(15, 'Stets freundlich und geduldig bleiben.', true),
(15, 'Bei schwierigen Kunden sofort auflegen.', false),
(15, 'Kompetenz und Lösungsorientierung zeigen.', true),
-- 17 SINGLE_CHOICE
(17, 'Vorteil: hohe Interaktivität, Nachteil: teuer.', false),
(17, 'Vorteil: persönlich, Nachteil: an einen Ort gebunden.', false),
(17, 'Vorteil: günstig, Nachteil: geringe Reichweite.', false),
(17, 'Vorteil: ortsunabhängig, Nachteil: unpersönlich.', true),
(17, 'Vorteil: keine technischen Voraussetzungen, Nachteil: zeitaufwändig.', false),
-- 19 SINGLE_CHOICE
(19, 'Ein Verfahren zur Software-Lizenzierung.', false),
(19, 'Ein Tool zur Netzwerküberwachung.', false),
(19, 'Eine systematische Methode zur Bewertung von Alternativen.', true),
(19, 'Eine Methode zur Risikobewertung.', false),
(19, 'Ein Marketinginstrument zur Kundenbindung.', false),
-- 21 MULTIPLE_CHOICE
(21, 'Die Preise stark erhöhen.', false),
(21, 'Hohe Produktqualität sicherstellen.', true),
(21, 'Den Support einstellen.', false),
(21, 'Exzellenten Kundenservice bieten.', true),
(21, 'Ein Bonusprogramm einführen.', true),
-- 22 SINGLE_CHOICE
(22, 'Die Auswahl des Angebots mit dem besten Preis-Leistungs-Verhältnis.', true),
(22, 'Die Ermittlung des günstigsten Preises.', false),
(22, 'Die Überprüfung der Lieferantenbonität.', false),
(22, 'Die reine Auflistung aller Angebote.', false),
(22, 'Die Festlegung der eigenen Verkaufspreise.', false),
-- 24 SINGLE_CHOICE
(24, 'Typ 1 und Typ 2 sind identisch.', false),
(24, 'Typ 2 ist eine Weiterentwicklung von Typ 1.', false),
(24, 'Typ 1 läuft direkt auf der Hardware, Typ 2 benötigt ein Wirtsbetriebssystem.', true),
(24, 'Typ 2 ist schneller als Typ 1.', false),
(24, 'Typ 1 wird nur für Desktops verwendet, Typ 2 nur für Server.', false),
-- 26 MULTIPLE_CHOICE
(26, 'VGA', false),
(26, 'HDMI 2.1', true),
(26, 'S-Video', false),
(26, 'DisplayPort 1.4', true),
(26, 'DVI', false),
-- 27 SINGLE_CHOICE
(27, 'Anschluss für externe Wasserkühlung.', false),
(27, 'Kein Betriebssystem vorinstalliert.', false),
(27, 'Erweiterbarkeit durch Steckkarten.', false),
(27, 'Integrierter Akku, Display und Tastatur.', true),
(27, 'Mindestens 2 kg Gewicht.', false),
-- 29 SINGLE_CHOICE
(29, 'Verdopplung der Speicherkapazität.', false),
(29, 'Erhöhung der Speicherbandbreite durch parallelen Zugriff.', true),
(29, 'Reduziert den Stromverbrauch des RAMs.', false),
(29, 'Verringerung der Latenz.', false),
(29, 'Ermöglicht den Einbau von unterschiedlichen RAM-Typen.', false),
-- 31 SINGLE_CHOICE
(31, 'Ein besonders leiser Computer.', false),
(31, 'Ein Endgerät mit minimaler lokaler Rechenleistung, das auf einen Server zugreift.', true),
(31, 'Ein Notebook mit Touchscreen.', false),
(31, 'Ein Server mit besonders viel Festplattenspeicher.', false),
(31, 'Ein Client mit mehreren Netzwerkkarten.', false),
-- 32 MULTIPLE_CHOICE
(32, 'Drucker', false),
(32, 'Maus', true),
(32, 'Tastatur', true),
(32, 'Monitor', false),
(32, 'Scanner', true),
-- 34 SINGLE_CHOICE
(34, 'IaaS, PaaS, SaaS.', false),
(34, 'Small, Medium, Large.', false),
(34, 'On-Premise, Off-Premise.', false),
(34, 'Public, Private, Hybrid, Community.', true),
(34, 'Personal, Business, Enterprise.', false),
-- 36 SINGLE_CHOICE
(36, 'Bereitstellung von fertiger Anwendungssoftware.', false),
(36, 'Verwaltung von Benutzerkonten.', false),
(36, 'Bereitstellung von virtualisierter IT-Infrastruktur (Rechenleistung, Speicher).', true),
(36, 'Bereitstellung einer kompletten Entwicklungsumgebung.', false),
(36, 'Automatisierte Installation von Betriebssystemen.', false),
-- 37 MULTIPLE_CHOICE
(37, 'Schnellere Anwendungsentwicklung und -bereitstellung.', true),
(37, 'Volle Kontrolle über das zugrundeliegende Betriebssystem.', false),
(37, 'Geringerer administrativer Aufwand für die Plattform.', true),
(37, 'Kostenlose Nutzung aller Dienste.', false),
(37, 'Einfache Skalierbarkeit von Anwendungen.', true),
-- 39 SINGLE_CHOICE
(39, 'Ein Controller für den Systembus.', false),
(39, 'Eine Karte, die einen Host mit einem Storage-Netzwerk (z.B. FC) verbindet.', true),
(39, 'Ein USB-Adapter für externe Geräte.', false),
(39, 'Eine Netzwerkkarte für Glasfaserverbindungen.', false),
(39, 'Ein Adapter zur Verbindung von Festplatten.', false),
-- 41 SINGLE_CHOICE
(41, 'Die Kühlung von Serverräumen.', false),
(41, 'Die Verwaltung von Benutzerrechten.', false),
(41, 'Sicherstellung der Stromversorgung bei Netzausfall.', true),
(41, 'Die Bereitstellung von Internetverbindungen.', false),
(41, 'Die Verschlüsselung von Daten.', false),
-- 43 SINGLE_CHOICE
(43, 'Ein separates Netzwerksegment, das als Pufferzone zwischen internem und externem Netz dient.', true),
(43, 'Ein physisches Netzwerk für besonders sensible Daten.', false),
(43, 'Ein virtuelles privates Netzwerk (VPN).', false),
(43, 'Ein drahtloses Netzwerk für Gäste.', false),
(43, 'Ein Speicherbereich für temporäre Dateien.', false),
-- 45 SINGLE_CHOICE
(45, 'Routing der Datenpakete durch das Netzwerk.', false),
(45, 'Physikalische Übertragung der Bits.', false),
(45, 'Steuerung der Dialoge zwischen Anwendungen.', false),
(45, 'Segmentierung der Daten und Flusskontrolle.', true),
(45, 'Darstellung der Daten und Verschlüsselung.', false),
-- 47 SINGLE_CHOICE
(47, 'Ein virtueller Speicher im Arbeitsspeicher.', false),
(47, 'Ein an das Netzwerk angebundener Dateispeicher.', true),
(47, 'Ein Speicher, der direkt an einen Server angeschlossen ist.', false),
(47, 'Ein Netzwerk aus Speichersystemen.', false),
(47, 'Ein Backup-System auf Bandlaufwerken.', false),
-- 49 SINGLE_CHOICE
(49, '255.255.255.192', false),
(49, '255.255.255.240', false),
(49, '255.255.255.0', false),
(49, '255.255.255.224', true),
(49, '255.255.255.128', false),
-- 51 SINGLE_CHOICE
(51, '192.168.1.10', false),
(51, 'C:\iscsi\target', false),
(51, 'eui.0123456789abcdef', false),
(51, '2001:db8::1', false),
(51, 'iqn (iSCSI Qualified Name).', true),
-- 53 SINGLE_CHOICE
(53, 'Kommunikation von einem Sender an eine ausgewählte Gruppe von Empfängern.', false),
(53, '1-zu-1-Kommunikation zwischen einem Sender und einem Empfänger.', true),
(53, 'Kommunikation ohne festen Empfänger.', false),
(53, 'Kommunikation von einem Sender an alle Empfänger im Netz.', false),
(53, 'Kommunikation zwischen zwei Routern.', false),
-- 55 SINGLE_CHOICE
(55, 'Eine Nachricht wird an ein bestimmtes Gerät gesendet.', false),
(55, 'Eine Nachricht wird nur innerhalb eines VLANs gesendet.', false),
(55, '1-zu-Alle-Kommunikation in einem Netzwerksegment.', true),
(55, 'Eine Nachricht wird verschlüsselt übertragen.', false),
(55, 'Eine Nachricht wird an eine Gruppe von Geräten gesendet.', false),
-- 57 SINGLE_CHOICE
(57, 'Sie besteht aus 32 Bit und wird dezimal dargestellt.', false),
(57, 'Sie ist weltweit eindeutig für jedes Gerät.', false),
(57, '128 Bit, hexadezimal, unterteilt in Netzwerkpräfix und Interface-ID.', true),
(57, 'Sie wird dynamisch vom DHCP-Server zugewiesen.', false),
(57, 'Sie besteht aus 48 Bit und wird für MAC-Adressen verwendet.', false),
-- 59 MULTIPLE_CHOICE
(59, 'Broadcast (wird durch Multicast ersetzt)', false),
(59, 'Global Unicast', true),
(59, 'Anycast', true),
(59, 'Link-Local Unicast', true),
(59, 'Multicast', true),
-- 60 SINGLE_CHOICE
(60, 'Ein Sicherheitsprotokoll für IPv6.', false),
(60, 'Ein Mechanismus zur Übersetzung von IPv4 in IPv6.', false),
(60, 'Automatische Adresskonfiguration ohne zentralen Server (DHCPv6).', true),
(60, 'Manuelle Konfiguration einer IPv6-Adresse.', false),
(60, 'Ein Verfahren zur Komprimierung von IPv6-Headern.', false),
-- 62 SINGLE_CHOICE
(62, 'Vorteil: Günstige Hardware, Nachteil: Geringe Reichweite.', false),
(62, 'Vorteil: Große Reichweite. Nachteil: Teure Hardware.', true),
(62, 'Vorteil: Unempfindlich gegen Abhören, Nachteil: Langsam.', false),
(62, 'Vorteil: Einfache Installation, Nachteil: Hohe Dämpfung.', false),
(62, 'Vorteil: Flexibel, Nachteil: Störanfällig.', false),
-- 64 SINGLE_CHOICE
(64, 'Überwachung und Steuerung von Netzwerkgeräten.', true),
(64, 'Sichere Übertragung von Dateien.', false),
(64, 'Auflösung von Domainnamen in IP-Adressen.', false),
(64, 'Automatische Vergabe von IP-Adressen.', false),
(64, 'Synchronisation der Uhrzeit im Netzwerk.', false),
-- 66 MULTIPLE_CHOICE
(66, 'IP-Adresse', true),
(66, 'Standardgateway', true),
(66, 'MAC-Adresse des Clients', false),
(66, 'Subnetzmaske', true),
(66, 'DNS-Server', true),
-- 67 SINGLE_CHOICE
(67, 'TCP ist verbindungsorientiert und zuverlässig, UDP ist verbindungslos und schnell.', true),
(67, 'TCP wird für DNS-Anfragen verwendet, UDP für Dateidownloads.', false),
(67, 'UDP ist sicherer als TCP.', false),
(67, 'Beide Protokolle sind identisch in ihrer Funktionsweise.', false),
(67, 'TCP arbeitet auf Schicht 3, UDP auf Schicht 4.', false),
-- 69 SINGLE_CHOICE
(69, 'Ein Maß für die Signalstärke eines WLANs.', false),
(69, 'Ein Sicherheitsprotokoll für VPNs.', false),
(69, 'Ein Standard für die Komprimierung von Videodaten.', false),
(69, 'Ein Verfahren zur Fehlerkorrektur bei der Datenübertragung.', false),
(69, 'Priorisierung von Datenverkehr zur Sicherstellung einer Dienstgüte.', true),
-- 71 MULTIPLE_CHOICE
(71, 'Alle Teilnehmer sind gleichberechtigt (Peer-to-Peer).', false),
(71, 'Zentralisierte Ressourcen und Datenhaltung auf dem Server.', true),
(71, 'Die Kommunikation erfolgt immer verschlüsselt.', false),
(71, 'Klare Trennung von Aufgaben zwischen Client und Server.', true),
(71, 'Clients fordern Dienste vom Server an.', true),
-- 72 SINGLE_CHOICE
(72, 'Vergabe von IP-Adressen an Clients.', false),
(72, 'Authentifizierung von Benutzern.', false),
(72, 'Namensauflösung von Hostnamen zu IP-Adressen.', true),
(72, 'Filterung von Netzwerkverkehr.', false),
(72, 'Speicherung von Benutzerdateien.', false),
-- 74 SINGLE_CHOICE
(74, 'Ein Router ist schneller als ein Switch.', false),
(74, 'Ein Switch verbindet Geräte im selben Netzwerk (Layer 2), ein Router verbindet verschiedene Netzwerke (Layer 3).', true),
(74, 'Ein Router kann WLAN, ein Switch nicht.', false),
(74, 'Ein Switch hat mehr Ports als ein Router.', false),
(74, 'Es gibt keinen Unterschied.', false),
-- 76 SINGLE_CHOICE
(76, 'Die USV ist nur für den Einsatz in Rechenzentren gedacht.', false),
(76, 'Die USV wird über das Netzwerk verwaltet.', false),
(76, 'Die USV schaltet nur bei einem Stromausfall auf Akkubetrieb um.', false),
(76, 'Die Geräte werden permanent über den Akku versorgt, der wiederum aus dem Netz geladen wird.', true),
(76, 'Die USV gleicht nur Spannungsschwankungen aus.', false),
-- 78 SINGLE_CHOICE
(78, 'Der Verschlüsselungsstandard eines WLANs.', false),
(78, 'Der Name eines WLAN-Netzwerks.', true),
(78, 'Das Passwort für ein WLAN-Netzwerk.', false),
(78, 'Die MAC-Adresse des Access Points.', false),
(78, 'Ein Protokoll zur Benutzerauthentifizierung.', false),
-- 80 MULTIPLE_CHOICE
(80, 'Installation eines größeren Monitors.', false),
(80, 'Einbau einer schnelleren CPU.', true),
(80, 'Erweiterung des Arbeitsspeichers (RAM).', true),
(80, 'Änderung der Gehäusefarbe.', false),
(80, 'Einbau einer SSD.', true),
-- 81 SINGLE_CHOICE
(81, 'Vorteil: Günstiger Preis, Nachteil: Geringe Kapazität.', false),
(81, 'Vorteil: Benötigt keine Treiber, Nachteil: Selten.', false),
(81, 'Vorteil: Sehr schnell, kompakt. Nachteil: Teurer, wird wärmer.', true),
(81, 'Vorteil: Kompatibel mit alten Systemen, Nachteil: Groß.', false),
(81, 'Vorteil: Lange Lebensdauer, Nachteil: Hoher Stromverbrauch.', false),
-- 83 SINGLE_CHOICE
(83, 'Der Arbeitsspeicher des Computers.', false),
(83, 'Ein kleiner, schneller Pufferspeicher direkt auf der CPU.', true),
(83, 'Der Speicher auf der Grafikkarte.', false),
(83, 'Ein externer Speicher für Backups.', false),
(83, 'Ein Cloud-Speicher.', false),
-- 86 SINGLE_CHOICE
(86, 'Spannung (U) / Stromstärke (I)', false),
(86, 'Spannung (U) * Kapazität (C)', false),
(86, 'P = U * I * cos(phi)', true),
(86, 'Widerstand (R) * Stromstärke (I)²', false),
(86, 'Leistung (P) * Zeit (t)', false),
-- 88 SINGLE_CHOICE
(88, 'Genau 15 Minuten.', false),
(88, 'Die Laufzeit verlängert sich.', false),
(88, 'Genau 60 Minuten.', false),
(88, 'Die Berechnung ist komplex und von vielen Faktoren abhängig.', true),
(88, 'Genau 30 Minuten.', false),
-- 90 SINGLE_CHOICE
(90, 'Er arbeitet ohne jegliche Verschlüsselung.', false),
(90, 'Er kann nur von einem einzigen Client gleichzeitig genutzt werden.', false),
(90, 'Er ist mit einem kabelgebundenen Netzwerk verbunden und dient als zentrale Brücke.', true),
(90, 'Er verbindet sich drahtlos mit einem anderen Access Point (Repeater-Modus).', false),
(90, 'Er erlaubt nur Verbindungen von Geräten mit bekannter MAC-Adresse.', false),
-- 92 SINGLE_CHOICE
(92, '1314,00 €', false),
(92, '876,00 €', false),
(92, '3504,00 €', false),
(92, '5256,00 €', false),
(92, '2628 EUR.', true),
-- 94 MULTIPLE_CHOICE
(94, '2.4 GHz hat eine höhere Reichweite als 5 GHz.', true),
(94, '5 GHz durchdringt Wände besser als 2.4 GHz.', false),
(94, '5GHz: höhere Geschwindigkeit, geringere Reichweite.', true),
(94, 'Beide Frequenzbänder sind identisch.', false),
(94, '2.4GHz: höhere Reichweite, mehr Störungen.', true),
-- 95 SINGLE_CHOICE
(95, 'Reichweite: ~100m, Datenrate: 1 Gbit/s.', false),
(95, 'Reichweite: ~1m, Datenrate: 10 kbit/s.', false),
(95, 'Reichweite und Datenrate sind unbegrenzt.', false),
(95, 'Bluetooth hat keine feste Spezifikation.', false),
(95, 'Abhängig von Klasse/Version, z.B. Klasse 2: ~10m, v5.0: bis zu 2 Mbit/s.', true),
-- 97 SINGLE_CHOICE
(97, 'Die Erhöhung der Anzahl von Servern zur Lastverteilung.', false),
(97, 'Reduzierung der Anzahl physischer Server durch Virtualisierung.', true),
(97, 'Die physikalische Zusammenlegung von Server-Racks.', false),
(97, 'Die Zusammenlegung mehrerer Datenbanken zu einer großen.', false),
(97, 'Die ausschließliche Nutzung von Cloud-Servern.', false),
-- 98 MULTIPLE_CHOICE
(98, 'Finanzielle Anforderungen (Was darf die Software kosten?)', false),
(98, 'Funktionale Anforderungen, Nicht-funktionale Anforderungen.', true),
(98, 'Design-Anforderungen (Wie soll die Software aussehen?)', false),
(98, 'Nicht-funktionale Anforderungen (Wie gut soll die Software es tun?)', false),
(98, 'Marketing-Anforderungen (Wie wird die Software beworben?)', false),
-- 100 SINGLE_CHOICE
(100, 'Leasing ist immer die günstigste Variante.', false),
(100, 'Kauf ist nur für kleine Unternehmen sinnvoll.', false),
(100, 'Pay-per-use bietet keine Flexibilität.', false),
(100, 'Alle drei Modelle sind kostenmäßig identisch.', false),
(100, 'Kauf: Eigentum, hohe Anfangskosten. Leasing: Feste Raten. Pay-per-use: Flexible, nutzungsabhängige Kosten.', true),
-- 101 SINGLE_CHOICE
(101, 'Bezugskalkulation, Selbstkostenkalkulation, Verkaufskalkulation.', true),
(101, 'Nur die Bezugskosten.', false),
(101, 'Nur die Verkaufspreise.', false),
(101, 'Nur die Produktionskosten.', false),
(101, 'Nur die Gewinnmarge.', false),
-- 102 SINGLE_CHOICE
(102, 'Die Analyse der Konkurrenz.', false),
(102, 'Die systematische Ermittlung der Anforderungen und Bedürfnisse des Kunden.', true),
(102, 'Die Erstellung eines Marketingplans.', false),
(102, 'Die Programmierung der Software.', false),
(102, 'Der Verkauf des fertigen Produkts.', false),
-- 103 SINGLE_CHOICE
(103, 'Vermeidung von Fehlentwicklungen, höhere Kundenzufriedenheit, solide Planungsgrundlage.', true),
(103, 'Nur höhere Kundenzufriedenheit.', false),
(103, 'Nur Vermeidung von Fehlentwicklungen.', false),
(103, 'Nur solide Planungsgrundlage.', false),
(103, 'Keine Vorteile, nur Nachteile.', false),
-- 104 SINGLE_CHOICE
(104, 'BIOS ist schneller als UEFI.', false),
(104, 'UEFI ist der Nachfolger von BIOS, bietet grafische Oberfläche, Secure Boot und unterstützt größere Festplatten.', true),
(104, 'UEFI und BIOS sind zwei Bezeichnungen für dasselbe.', false),
(104, 'BIOS unterstützt größere Festplatten als UEFI.', false),
(104, 'UEFI wird nur auf Apple-Geräten verwendet.', false),
-- 105 SINGLE_CHOICE
(105, 'Die Bildschirmausgabe eines entfernten Computers wird auf dem lokalen Client angezeigt und Eingaben werden übertragen.', true),
(105, 'Nur die Eingaben werden übertragen.', false),
(105, 'Nur die Bildschirmausgabe wird übertragen.', false),
(105, 'Die Verbindung erfolgt über Bluetooth.', false),
(105, 'Es ist eine reine Textverbindung.', false),
-- 106 SINGLE_CHOICE
(106, 'ipconfig /dns', false),
(106, 'netstat -r', false),
(106, 'nslookup, ping.', true),
(106, 'tracert <domain>', false),
(106, 'arp -a', false),
-- 107 MULTIPLE_CHOICE
(107, 'BitLocker', false),
(107, 'Secure Boot, Trusted Boot, Early Launch Anti-Malware (ELAM).', true),
(107, 'Windows Defender', false),
(107, 'Trusted Boot', false),
(107, 'Early Launch Anti-Malware (ELAM)', false),
-- 108 SINGLE_CHOICE
(108, 'Partitionierung teilt einen Datenträger in Bereiche. Formatierung erstellt ein Dateisystem in einer Partition.', true),
(108, 'Partitionierung formatiert den Datenträger.', false),
(108, 'Formatierung teilt den Datenträger in Partitionen.', false),
(108, 'Beides ist dasselbe.', false),
(108, 'Nur Formatierung ist notwendig.', false),
-- 109 SINGLE_CHOICE
(109, 'Die Seriennummer des Betriebssystems.', false),
(109, 'Ein Aufkleber mit dem Firmenlogo.', false),
(109, 'Der Name des Administrators.', false),
(109, 'Eine eindeutige Kennzeichnung zur Identifizierung von Hardware.', true),
(109, 'Ein QR-Code zur Website des Herstellers.', false),
-- 110 SINGLE_CHOICE
(110, 'Zentrale Verwaltung, geringere Kosten, höhere Sicherheit.', true),
(110, 'Nur höhere Sicherheit.', false),
(110, 'Nur geringere Kosten.', false),
(110, 'Nur zentrale Verwaltung.', false),
(110, 'Keine Vorteile.', false),
-- 111 SINGLE_CHOICE
(111, 'Beschreibt, WAS der Auftraggeber für Anforderungen hat.', false),
(111, 'Wird vom Auftraggeber erstellt.', false),
(111, 'Enthält nur die Kosten des Projekts.', false),
(111, 'Beschreibt, wie der Auftragnehmer die Anforderungen des Lastenhefts umsetzen wird.', true),
(111, 'Ist ein anderer Begriff für den Kaufvertrag.', false),
-- 112 SINGLE_CHOICE
(112, 'Vorteil: Flexibel, Kosten nach Nutzung. Nachteil: Schlecht kalkulierbar.', true),
(112, 'Nur Vorteile.', false),
(112, 'Nur Nachteile.', false),
(112, 'Immer teurer als Kauf.', false),
(112, 'Immer günstiger als Kauf.', false),
-- 113 SINGLE_CHOICE
(113, 'Beschreibt, wie der Auftragnehmer die Anforderungen umsetzen wird.', false),
(113, 'Wird vom Auftragnehmer erstellt.', false),
(113, 'Enthält den Quellcode der Anwendung.', false),
(113, 'Die Gesamtheit der Anforderungen des Auftraggebers an ein Projekt oder Produkt.', true),
(113, 'Ist ein Protokoll der Projektsitzungen.', false),
-- 114 SINGLE_CHOICE
(114, 'Ein Notebook, das sich auch als Tablet nutzen lässt (z.B. durch umklappbares Display).', true),
(114, 'Ein Tablet mit Tastatur.', false),
(114, 'Ein Notebook mit Touchscreen.', false),
(114, 'Ein faltbares Smartphone.', false),
(114, 'Ein spezieller E-Reader.', false),
-- 115 MULTIPLE_CHOICE
(115, 'Vorteil: Sehr mobil, intuitive Bedienung. Nachteil: Weniger Leistung, keine physische Tastatur.', true),
(115, 'Vorteil: Sehr mobil und leicht.', true),
(115, 'Nachteil: Weniger Leistung als Notebooks.', true),
(115, 'Nachteil: Oft keine physische Tastatur.', true),
(115, 'Vorteil: Einfach aufrüstbar.', false),
-- 116 SINGLE_CHOICE
(116, 'Vorteil: Günstig. Nachteil: Schwer.', false),
(116, 'Vorteil: Lange Akkulaufzeit. Nachteil: Kleines Display.', false),
(116, 'Vorteil: Unbegrenzte Leistung. Nachteil: Hoher Preis.', false),
(116, 'Vorteil: Mobil und leistungsstark. Nachteil: Begrenzte Aufrüstbarkeit, teurer als Desktop.', true),
(116, 'Vorteil: Einfache Reparatur. Nachteil: Wenig Software.', false),
-- 117 SINGLE_CHOICE
(117, 'Hohe Speicherkapazität, Verfügbarkeit, Datensicherheit, schnelle Netzwerkverbindung.', true),
(117, 'Nur hohe Speicherkapazität.', false),
(117, 'Nur schnelle Netzwerkverbindung.', false),
(117, 'Nur Datensicherheit.', false),
(117, 'Keine besonderen Anforderungen.', false),
-- 118 SINGLE_CHOICE
(118, 'SDSL ist immer schneller als VDSL.', false),
(118, 'ADSL verwendet Glasfaser, VDSL und SDSL Kupferkabel.', false),
(118, 'ADSL/VDSL: asymmetrisch (Download > Upload). SDSL: symmetrisch.', true),
(118, 'Alle drei sind identische Technologien.', false),
(118, 'VDSL ist ein reiner Mobilfunkstandard.', false),
-- 119 SINGLE_CHOICE
(119, 'ca. 5 Minuten 44 Sekunden.', true),
(119, 'ca. 1 Minute.', false),
(119, 'ca. 10 Minuten.', false),
(119, 'ca. 30 Sekunden.', false),
(119, 'ca. 2 Stunden.', false),
-- 120 SINGLE_CHOICE
(120, 'Nur auf den niedrigsten Preis.', false),
(120, 'Nur auf die Marke des Herstellers.', false),
(120, 'Anforderungen, Kompatibilität, Kosten, Garantie, Service.', true),
(120, 'Nur auf die Farbe des Gehäuses.', false),
(120, 'Nur auf die Verfügbarkeit beim lokalen Händler.', false),
-- 121 SINGLE_CHOICE
(121, 'Software, die für einen breiten Markt und nicht für einen speziellen Kunden entwickelt wurde.', true),
(121, 'Software, die kostenlos ist.', false),
(121, 'Software, die nur von einem Unternehmen genutzt wird.', false),
(121, 'Software, die speziell für einen Kunden entwickelt wird.', false),
(121, 'Software, die Open Source ist.', false),
-- 122 SINGLE_CHOICE
(122, 'Software, die kostenlos im Internet verfügbar ist.', false),
(122, 'Software, die auf jedem Betriebssystem läuft.', false),
(122, 'Software, die als Standard für eine ganze Branche gilt.', false),
(122, 'Software, die speziell für die Anforderungen eines einzelnen Kunden entwickelt wird.', true),
(122, 'Software, die von einem großen Hersteller wie Microsoft oder Adobe stammt.', false),
-- 123 SINGLE_CHOICE
(123, 'Integrated Development Environment (Integrierte Entwicklungsumgebung).', true),
(123, 'Internet Download Manager.', false),
(123, 'International Data Exchange.', false),
(123, 'Internal Drive Encryption.', false),
(123, 'Information Display Element.', false),
-- 124 SINGLE_CHOICE
(124, 'Software, deren Quellcode frei verfügbar ist.', false),
(124, 'Software, die nur auf bestimmter Hardware läuft.', false),
(124, 'Software, deren Nutzung, Weitergabe und Veränderung rechtlich eingeschränkt ist.', true),
(124, 'Software, die von der Community entwickelt wird.', false),
(124, 'Software, die kostenlos ist.', false),
-- 125 MULTIPLE_CHOICE
(125, 'Der Quellcode ist öffentlich zugänglich.', true),
(125, 'Die Software ist immer kostenlos.', false),
(125, 'Die Software darf frei kopiert und weitergegeben werden.', true),
(125, 'Es gibt keinen Support für die Software.', false),
(125, 'Die Software darf verändert und verbessert werden.', true),
-- 126 SINGLE_CHOICE
(126, 'Software/Hardware, die für den Verkauf zusammen mit einem anderen Produkt (z.B. PC) bestimmt ist.', true),
(126, 'Nur Software.', false),
(126, 'Nur Hardware.', false),
(126, 'Software, die nur online verkauft wird.', false),
(126, 'Hardware, die nur für den Export bestimmt ist.', false),
-- 127 SINGLE_CHOICE
(127, 'Die Fähigkeit eines Systems, bei steigender Last die Leistung entsprechend zu erhöhen.', true),
(127, 'Die Fähigkeit, verschiedene Betriebssysteme zu unterstützen.', false),
(127, 'Die Größe des Rechenzentrums.', false),
(127, 'Die Geschwindigkeit der Internetanbindung.', false),
(127, 'Die Anzahl der Mitarbeiter im Rechenzentrum.', false),
-- 128 SINGLE_CHOICE
(128, 'Den Lizenzvertrag zwischen Softwarehersteller und Endbenutzer.', true),
(128, 'Die Garantiebedingungen für Hardware.', false),
(128, 'Die Nutzungsrichtlinien für das Internet.', false),
(128, 'Die Sicherheitsbestimmungen für das Netzwerk.', false),
(128, 'Das Handbuch für die Software.', false),
-- 129 SINGLE_CHOICE
(129, 'Man zahlt eine feste monatliche Pauschale.', false),
(129, 'Man kauft die Software einmalig.', false),
(129, 'Die Nutzung ist immer kostenlos.', false),
(129, 'Bezahlung von Diensten basierend auf der tatsächlichen Nutzung.', true),
(129, 'Man bezahlt pro installiertem Computer.', false),
-- 130 MULTIPLE_CHOICE
(130, 'Starke Verschlüsselung (WPA2/WPA3)', true),
(130, 'Ein sicheres, langes Passwort', true),
(130, 'Keine Verschlüsselung für höhere Geschwindigkeit', false),
(130, 'SSID nicht broadcasten', true),
(130, 'MAC-Filter', true),
-- 131 SINGLE_CHOICE
(131, 'Site-to-Site, End-to-Site (Remote Access), End-to-End.', true),
(131, 'Nur Site-to-Site.', false),
(131, 'Nur End-to-Site.', false),
(131, 'Nur End-to-End.', false),
(131, 'Es gibt nur eine Art.', false),
-- 132 SINGLE_CHOICE
(132, 'Ein physisch getrenntes, privates Netzwerk.', false),
(132, 'Ein besonders schnelles Netzwerk.', false),
(132, 'Sicherer, verschlüsselter Tunnel durch ein unsicheres Netzwerk (z.B. Internet).', true),
(132, 'Ein drahtloses Netzwerk.', false),
(132, 'Ein Netzwerk ohne Internetzugang.', false),
-- 133 SINGLE_CHOICE
(133, 'WPA2, WPA3 mit AES-Verschlüsselung.', true),
(133, 'Nur WEP.', false),
(133, 'Keine Verschlüsselung.', false),
(133, 'WPA mit TKIP.', false),
(133, 'Nur WPA3.', false),
-- 134 SINGLE_CHOICE
(134, 'Erhöhung der Bandbreite im Netzwerk.', false),
(134, 'Automatische Zuweisung von IP-Adressen.', false),
(134, 'Schutz vor Viren und Malware.', false),
(134, 'Logische Segmentierung des Netzwerks, höhere Sicherheit, besseres Management.', true),
(134, 'Physische Trennung von Netzwerkkabeln.', false),
-- 135 SINGLE_CHOICE
(135, 'Anzeige und Bearbeitung des ARP-Caches (Zuordnung IP- zu MAC-Adresse).', true),
(135, 'Anzeige der Routing-Tabelle.', false),
(135, 'Anzeige der offenen Netzwerkverbindungen.', false),
(135, 'Anzeige der DNS-Einträge.', false),
(135, 'Anzeige der IP-Adressen.', false),
-- 136 SINGLE_CHOICE
(136, 'Änderung der Dateizugriffsrechte (Lesen, Schreiben, Ausführen).', true),
(136, 'Anzeige des aktuellen Verzeichnisses.', false),
(136, 'Löschen von Dateien.', false),
(136, 'Anzeige des Dateiinhalts.', false),
(136, 'Änderung des Dateibesitzers.', false),
-- 137 SINGLE_CHOICE
(137, 'Self-Monitoring, Analysis and Reporting Technology (System zur Selbstüberwachung).', true),
(137, 'Secure Mode Access Reporting Tool.', false),
(137, 'System Management and Reporting Tool.', false),
(137, 'Storage Monitoring and Analysis Routine.', false),
(137, 'System Maintenance and Repair Tool.', false),
-- 138 MULTIPLE_CHOICE
(138, 'P.O.S.T. -> Bootreihenfolge festlegen -> EULA akzeptieren -> Partitionieren/Formatieren -> Benutzer anlegen.', true),
(138, 'Bootreihenfolge festlegen -> P.O.S.T. -> Benutzer anlegen -> EULA akzeptieren -> Partitionieren/Formatieren.', false),
(138, 'EULA akzeptieren -> P.O.S.T. -> Partitionieren/Formatieren -> Benutzer anlegen -> Bootreihenfolge festlegen.', false),
(138, 'Partitionieren/Formatieren -> Benutzer anlegen -> P.O.S.T. -> Bootreihenfolge festlegen -> EULA akzeptieren.', false),
(138, 'Benutzer anlegen -> EULA akzeptieren -> P.O.S.T. -> Bootreihenfolge festlegen -> Partitionieren/Formatieren.', false),
-- 139 SINGLE_CHOICE
(139, 'ip addr, ifconfig.', true),
(139, 'netstat', false),
(139, 'ping', false),
(139, 'traceroute', false),
(139, 'hostname', false),
-- 140 SINGLE_CHOICE
(140, 'netsh interface ipv4 set address name="LAN-Verbindung" static 192.168.0.1 255.255.255.0 192.168.0.254', true),
(140, 'ipconfig /set address 192.168.0.1', false),
(140, 'route add 192.168.0.0 mask 255.255.255.0 192.168.0.254', false),
(140, 'netsh interface ip set address name="LAN-Verbindung" static 192.168.0.1 255.255.255.0', false),
(140, 'set ipaddress 192.168.0.1', false),
-- 141 SINGLE_CHOICE
(141, 'Unterschiedliche RAM-Größen kombinieren.', false),
(141, 'Nur einen RAM-Riegel verwenden.', false),
(141, 'Die Module in beliebige Slots stecken.', false),
(141, 'Zwei identische oder technisch sehr ähnliche RAM-Module in den richtigen Slots.', true),
(141, 'Den Arbeitsspeicher übertakten.', false),
-- 142 SINGLE_CHOICE
(142, 'Unified Modeling Language.', true),
(142, 'Universal Management Layer.', false),
(142, 'User Modeling Language.', false),
(142, 'Unified Method Language.', false),
(142, 'Uniform Modeling Language.', false),
-- 143 MULTIPLE_CHOICE
(143, 'Klassendiagramm (Class Diagram)', false),
(143, 'Anwendungsfalldiagramm (Use Case Diagram)', true),
(143, 'Sequenzdiagramm (Sequence Diagram)', true),
(143, 'Komponentendiagramm (Component Diagram)', false),
(143, 'Aktivitätsdiagramm (Activity Diagram)', true),
-- 144 SINGLE_CHOICE
(144, 'Ein Objekt ist der Bauplan, eine Klasse ist die Instanz.', false),
(144, 'Klasse und Objekt sind dasselbe.', false),
(144, 'Klassen werden zur Laufzeit erstellt, Objekte beim Kompilieren.', false),
(144, 'Eine Klasse ist ein Bauplan, ein Objekt ist die daraus erstellte Instanz dieses Bauplans.', true),
(144, 'Objekte können keine Methoden haben, Klassen schon.', false),
-- 145 SINGLE_CHOICE
(145, 'Nur Datenpersistenz.', false),
(145, 'Nur Datenintegrität.', false),
(145, 'Nur Datensicherheit.', false),
(145, 'Nur Mehrbenutzerzugriff.', false),
(145, 'Datenpersistenz, Datenintegrität, Datensicherheit, Mehrbenutzerzugriff.', true),
-- 146 SINGLE_CHOICE
(146, '1NF: Keine Redundanz. 2NF: Fremdschlüssel. 3NF: Primärschlüssel.', false),
(146, '1NF: Nur Text. 2NF: Nur Zahlen. 3NF: Beides.', false),
(146, 'Die Normalformen dienen der Beschleunigung von Abfragen.', false),
(146, '1NF: Atomare Werte. 2NF: Keine partiellen Abhängigkeiten. 3NF: Keine transitiven Abhängigkeiten.', true),
(146, 'Es gibt nur eine Normalform.', false),
-- 147 SINGLE_CHOICE
(147, 'DDL: CREATE TABLE, DML: INSERT, DQL: SELECT.', true),
(147, 'DDL: INSERT, DML: SELECT, DQL: CREATE TABLE.', false),
(147, 'DDL: SELECT, DML: CREATE TABLE, DQL: INSERT.', false),
(147, 'DDL: UPDATE, DML: DELETE, DQL: ALTER TABLE.', false),
(147, 'Alle sind dasselbe.', false),
-- 148 SINGLE_CHOICE
(148, 'Der Betrieb ist besonders umweltfreundlich.', false),
(148, 'Der Betrieb zahlt hohe Steuern.', false),
(148, 'Alle Produkte des Betriebs sind fehlerfrei.', false),
(148, 'Der Betrieb hat ein zertifiziertes Qualitätsmanagementsystem.', true),
(148, 'Der Betrieb ist Marktführer in seiner Branche.', false),
-- 149 SINGLE_CHOICE
(149, 'Ein Projektmanagement-Framework.', false),
(149, 'Ein IT-Sicherheitsstandard.', false),
(149, 'Ein Verfahren zur Softwareentwicklung.', false),
(149, 'Plan-Do-Check-Act: Ein Zyklus zur kontinuierlichen Verbesserung.', true),
(149, 'Eine Methode zur Personalbeurteilung.', false),
-- 150 SINGLE_CHOICE
(150, 'Ein Label für recycelte Produkte.', false),
(150, 'Ein Fair-Trade-Siegel.', false),
(150, 'Ein Bio-Siegel für Lebensmittel.', false),
(150, 'Ein Label für besonders energieeffiziente Elektrogeräte.', true),
(150, 'Ein Preis für innovatives Design.', false),
-- 151 SINGLE_CHOICE
(151, 'Eine systematische Untersuchung, ob Prozesse und Ergebnisse den Anforderungen entsprechen.', true),
(151, 'Nur die Überprüfung der Ergebnisse.', false),
(151, 'Nur die Überprüfung der Prozesse.', false),
(151, 'Eine reine Dokumentenprüfung.', false),
(151, 'Eine Kundenbefragung.', false),
-- 152 MULTIPLE_CHOICE
(152, 'Funktionalität, Zuverlässigkeit, Benutzbarkeit, Effizienz, Wartbarkeit, Portabilität.', true),
(152, 'Nur Funktionalität.', false),
(152, 'Nur Zuverlässigkeit.', false),
(152, 'Nur Benutzbarkeit.', false),
(152, 'Nur Effizienz.', false),
-- 153 SINGLE_CHOICE
(153, 'Es ist ein internationales Umweltsiegel.', false),
(153, 'Es wird von der Stiftung Warentest vergeben.', false),
(153, 'Es zertifiziert die biologische Herkunft von Lebensmitteln.', false),
(153, 'Es bestätigt, dass ein Produkt die Anforderungen des deutschen Produktsicherheitsgesetzes erfüllt.', true),
(153, 'Es ist ein Preis für besonders gutes Design.', false),
-- 154 SINGLE_CHOICE
(154, 'Ein Umweltzeichen für besonders umweltschonende Produkte und Dienstleistungen.', true),
(154, 'Ein Siegel für fairen Handel.', false),
(154, 'Ein Zeichen für hohe Energieeffizienz.', false),
(154, 'Ein Qualitätssiegel für Elektronik.', false),
(154, 'Ein Siegel für biologische Produkte.', false),
-- 155 SINGLE_CHOICE
(155, 'Die Geräte einfach in den Hausmüll werfen.', false),
(155, 'Die Geräte an Freunde und Familie verschenken.', false),
(155, 'Fachgerechte Entsorgung gemäß Elektroschrottverordnung, Datensicherheit.', true),
(155, 'Die Geräte im Keller lagern.', false),
(155, 'Die Festplatten ausbauen und als Untersetzer verwenden.', false),
-- 156 SINGLE_CHOICE
(156, 'Nur die Festplatten ausbauen.', false),
(156, 'Die Geräte einfach wegwerfen.', false),
(156, 'Sichere und irreversible Datenlöschung.', true),
(156, 'Die Daten nur kopieren.', false),
(156, 'Die Geräte verkaufen.', false),
-- 157 SINGLE_CHOICE
(157, 'Anmeldung mit zwei verschiedenen Passwörtern.', false),
(157, 'Authentifizierung mit mindestens zwei unterschiedlichen Faktoren (Wissen, Besitz, Sein).', true),
(157, 'Anmeldung von zwei verschiedenen Geräten aus.', false),
(157, 'Ein besonders langes und komplexes Passwort.', false),
(157, 'Die Authentifizierung durch einen Administrator.', false),
-- 158 SINGLE_CHOICE
(158, 'Schutz von Daten. Schutzziele: Vertraulichkeit, Integrität, Verfügbarkeit.', true),
(158, 'Nur Schutz vor Viren.', false),
(158, 'Nur Schutz vor unbefugtem Zugriff.', false),
(158, 'Nur Sicherstellung der Verfügbarkeit.', false),
(158, 'Nur Sicherstellung der Integrität.', false),
-- 159 SINGLE_CHOICE
(159, 'Es gibt keinen Unterschied.', false),
(159, 'Datensicherheit ist ein Teil des Datenschutzes.', false),
(159, 'Datenschutz ist ein Teil der Datensicherheit.', false),
(159, 'Datensicherheit schützt Daten vor unbefugtem Zugriff (technisch), Datenschutz schützt die Persönlichkeitsrechte von Personen (rechtlich).', true),
(159, 'Beides wird durch die Firewall geregelt.', false),
-- 160 SINGLE_CHOICE
(160, 'Konkrete Maßnahmen zur Umsetzung der Datensicherheit.', true),
(160, 'Nur organisatorische Maßnahmen.', false),
(160, 'Nur technische Maßnahmen.', false),
(160, 'Die Datenschutzgesetze.', false),
(160, 'Die Schulung der Mitarbeiter.', false),
-- 161 MULTIPLE_CHOICE
(161, 'Zutrittskontrolle (physisch)', true),
(161, 'Zugangskontrolle (logisch, z.B. Passwort)', true),
(161, 'Schöne Büromöbel', false),
(161, 'Zugriffskontrolle (Berechtigungen)', true),
(161, 'Verschlüsselung', true),
-- 162 SINGLE_CHOICE
(162, 'Garantie für absolute Sicherheit.', false),
(162, 'Erhöhung der Verkaufszahlen.', false),
(162, 'Nachweis eines hohen IT-Sicherheitsniveaus, Vertrauensbildung, Risikominimierung.', true),
(162, 'Möglichkeit, höhere Preise zu verlangen.', false),
(162, 'Einsparung von Personalkosten.', false),
-- 163 SINGLE_CHOICE
(163, 'Nur so viele personenbezogene Daten wie für den Zweck nötig erheben und verarbeiten.', true),
(163, 'Alle verfügbaren Daten erheben.', false),
(163, 'Die Datenmenge spielt keine Rolle.', false),
(163, 'Die Datenmenge nur für die Rechnungsstellung minimieren.', false),
(163, 'Die Datenmenge nur für Marketingzwecke minimieren.', false),
-- 164 MULTIPLE_CHOICE
(164, 'Recht auf Auskunft, Berichtigung, Löschung, Datenübertragbarkeit.', true),
(164, 'Recht auf ein kostenloses Smartphone', false),
(164, 'Recht auf Berichtigung', false),
(164, 'Recht auf Löschung', false),
(164, 'Recht auf Datenübertragbarkeit', false),
-- 165 SINGLE_CHOICE
(165, 'Ein privater Schlüssel zur Verschlüsselung.', false),
(165, 'Ein System zur Verwaltung und Nutzung von digitalen Zertifikaten.', true),
(165, 'Eine Abteilung in einem Unternehmen, die für die IT-Sicherheit zuständig ist.', false),
(165, 'Ein besonders sicherer Computer.', false),
(165, 'Ein Protokoll zur Datenübertragung.', false),
-- 166 SINGLE_CHOICE
(166, 'Ein elektronischer Echtheitsnachweis für einen öffentlichen Schlüssel.', true),
(166, 'Ein Passwort für den Zugriff auf Schlüssel.', false),
(166, 'Eine Liste aller gültigen Schlüssel.', false),
(166, 'Ein Programm zur Schlüsselverwaltung.', false),
(166, 'Ein Zertifikat für die Netzwerkverbindung.', false),
-- 167 SINGLE_CHOICE
(167, 'Eine Firewall, die nur Pakete von bekannten IP-Adressen durchlässt.', false),
(167, 'Eine Firewall, die den gesamten Datenverkehr blockiert.', false),
(167, 'Eine persönliche Firewall auf einem Client-PC.', false),
(167, 'Eine Hardware-Firewall.', false),
(167, 'Eine Firewall, die den Zustand von Verbindungen verfolgt und Pakete kontextbasiert filtert.', true),
-- 168 SINGLE_CHOICE
(168, 'Schutz von Endgeräten (PCs, Laptops, Smartphones).', true),
(168, 'Schutz von Servern.', false),
(168, 'Schutz von Netzwerkinfrastruktur.', false),
(168, 'Schutz von Cloud-Daten.', false),
(168, 'Schutz von Softwareanwendungen.', false),
-- 169 MULTIPLE_CHOICE
(169, 'Verschlüsselung von Festplatten', false),
(169, 'Passwortspeicherung', true),
(169, 'Erstellung digitaler Signaturen', true),
(169, 'Authentifizierung von Benutzern', false),
(169, 'Sicherstellung der Datenintegrität', true),
-- 170 SINGLE_CHOICE
(170, 'Erstellung digitaler Signaturen.', false),
(170, 'Authentifizierung von Webservern.', false),
(170, 'Schlüsselaustausch.', false),
(170, 'Verschlüsselung großer Datenmengen, z.B. mit AES.', true),
(170, 'Passwortspeicherung.', false),
-- 171 SINGLE_CHOICE
(171, 'Differentiell: sichert Änderungen seit letztem Voll-Backup. Inkrementell: sichert Änderungen seit letztem Backup.', true),
(171, 'Differentiell sichert alles seit dem letzten Backup.', false),
(171, 'Inkrementell sichert alles seit dem letzten Voll-Backup.', false),
(171, 'Beide sind dasselbe.', false),
(171, 'Nur inkrementelle Backups sind sinnvoll.', false),
-- 172 SINGLE_CHOICE
(172, 'Nur tägliche Sicherungen.', false),
(172, 'Nur wöchentliche Sicherungen.', false),
(172, 'Nur monatliche Sicherungen.', false),
(172, 'Tägliche (Sohn), wöchentliche (Vater) und monatliche (Großvater) Sicherungen.', true),
(172, 'Ein einmaliges Backup am Anfang.', false),
-- 173 SINGLE_CHOICE
(173, 'Malware: Oberbegriff. Ransomware: Erpressersoftware. Trojaner: Getarnte Schadsoftware.', true),
(173, 'Alle sind dasselbe.', false),
(173, 'Malware ist nur Ransomware.', false),
(173, 'Trojaner sind immer harmlos.', false),
(173, 'Ransomware ist eine Art von Trojaner.', false),
-- 174 SINGLE_CHOICE
(174, 'Die Installation von Virenscannern.', false),
(174, 'Die Schulung von Mitarbeitern.', false),
(174, 'Die Reaktion auf Sicherheitsvorfälle.', false),
(174, 'Planung, Steuerung, Kontrolle und Verbesserung der IT-Sicherheit.', true),
(174, 'Die Erstellung von Backups.', false),
-- 175 MULTIPLE_CHOICE
(175, 'Mindestlänge', true),
(175, 'Passwort muss der Benutzername sein', false),
(175, 'Komplexität (Zahlen, Sonderzeichen etc.)', true),
(175, 'Regelmäßiger Wechsel', true),
(175, 'Verbot von Trivialpasswörtern', true),
-- 176 SINGLE_CHOICE
(176, 'Integration von Sicherheit von Anfang an in den Entwicklungsprozess.', true),
(176, 'Sicherheit wird erst am Ende geprüft.', false),
(176, 'Sicherheit ist nur für die Hardware relevant.', false),
(176, 'Sicherheit ist nur für die Software relevant.', false),
(176, 'Sicherheit ist optional.', false),
-- 177 SINGLE_CHOICE
(177, 'Personal: Einfach, aber unsicherer. Enterprise: Sicher, aber komplexer.', true),
(177, 'Enterprise ist einfacher zu konfigurieren.', false),
(177, 'Personal ist sicherer als Enterprise.', false),
(177, 'Beide sind identisch sicher.', false),
(177, 'WPA2 ist veraltet und sollte nicht mehr verwendet werden.', false),
-- 178 SINGLE_CHOICE
(178, 'Verschlüsselung (TLS, S/MIME), Spam-Filter, Virenscanner.', true),
(178, 'Nur Spam-Filter.', false),
(178, 'Nur Virenscanner.', false),
(178, 'Nur Verschlüsselung.', false),
(178, 'Keine Maßnahmen notwendig.', false),
-- 179 SINGLE_CHOICE
(179, 'Richtige Tisch-/Stuhlhöhe, matter Bildschirm, gute Beleuchtung.', true),
(179, 'Ein möglichst großer Monitor.', false),
(179, 'Ein besonders weicher Bürostuhl.', false),
(179, 'Möglichst viele Pflanzen im Büro.', false),
(179, 'Ein Fensterplatz mit direkter Sonneneinstrahlung.', false),
-- 180 SINGLE_CHOICE
(180, 'Bildschirm: flimmerfrei, reflexionsarm. Tastatur: neigbar, getrennt.', true),
(180, 'Nur flimmerfreier Bildschirm.', false),
(180, 'Nur reflexionsarmer Bildschirm.', false),
(180, 'Nur neigbare Tastatur.', false),
(180, 'Nur getrennte Tastatur.', false),
-- 181 SINGLE_CHOICE
(181, 'Ein Projektmanagement-Framework.', false),
(181, 'Ein IT-Sicherheitsstandard.', false),
(181, 'Ein Verfahren zur Softwareentwicklung.', false),
(181, 'Plan, Do, Check, Act - ein kontinuierlicher Verbesserungsprozess.', true),
(181, 'Eine Methode zur Personalbeurteilung.', false),
-- 182 SINGLE_CHOICE
(182, 'Spezifisch, Messbar, Akzeptiert, Realistisch, Terminiert.', true),
(182, 'Schnell, Messbar, Attraktiv, Realistisch, Terminiert.', false),
(182, 'Spezifisch, Modern, Akzeptiert, Robust, Terminiert.', false),
(182, 'Spezifisch, Messbar, Angenehm, Regelmäßig, Terminiert.', false),
(182, 'Spezifisch, Messbar, Erreichbar, Relevant, Terminiert.', false),
-- 183 MULTIPLE_CHOICE
(183, 'Weiterbildung, gutes Arbeitsklima, ergonomische Arbeitsplätze.', true),
(183, 'Ständige Überstunden', false),
(183, 'Ein positives und unterstützendes Arbeitsklima', true),
(183, 'Ergonomische Arbeitsplätze', true),
(183, 'Klare und erreichbare Ziele', true),
-- 184 SINGLE_CHOICE
(184, 'Qualitätsmanagement, Tests, Kundenfeedback, KVP.', true),
(184, 'Verzicht auf Produkttests, um Kosten zu sparen.', false),
(184, 'Ignorieren von Kundenfeedback.', false),
(184, 'Reduzierung der Ausgaben für Forschung und Entwicklung.', false),
(184, 'Einstellung von unqualifiziertem Personal.', false),
-- 185 SINGLE_CHOICE
(185, 'Vertraulichkeit, Integrität, Verfügbarkeit.', true),
(185, 'Nur Vertraulichkeit.', false),
(185, 'Nur Integrität.', false),
(185, 'Nur Verfügbarkeit.', false),
(185, 'Kosten und Zeit.', false),
-- 186 SINGLE_CHOICE
(186, 'Normal: Kein Schaden. Hoch: Kleiner Schaden. Sehr hoch: Großer Schaden.', false),
(186, 'Die Kategorien beziehen sich auf die Kosten der Hardware.', false),
(186, 'Normal: Schaden ist begrenzt. Hoch: Schaden ist beträchtlich. Sehr hoch: Schaden ist existenzbedrohend.', true),
(186, 'Die Kategorien werden nach der Anzahl der Benutzer eingeteilt.', false),
(186, 'Normal: Privat. Hoch: Geschäftlich. Sehr hoch: Militärisch.', false),
-- 187 SINGLE_CHOICE
(187, 'Hohe Verfügbarkeit, hohe Integrität, normale Vertraulichkeit.', true),
(187, 'Nur hohe Verfügbarkeit.', false),
(187, 'Nur hohe Integrität.', false),
(187, 'Nur normale Vertraulichkeit.', false),
(187, 'Sehr hohe Vertraulichkeit, Integrität und Verfügbarkeit.', false),
-- 188 MULTIPLE_CHOICE
(188, 'Firewall, Virenschutz, Backups, Zutrittskontrolle.', true),
(188, 'Passwörter auf Post-its am Monitor anbringen', false),
(188, 'Virenschutz', false),
(188, 'Regelmäßige Backups', false),
(188, 'Zutrittskontrolle zum Serverraum', false),
-- 189 SINGLE_CHOICE
(189, 'Analyse, Design, Implementierung, Test, Wartung.', false),
(189, 'Planung, Durchführung, Kontrolle, Abschluss.', false),
(189, 'Beschaffung, Installation, Konfiguration, Betrieb.', false),
(189, 'Initiierung, Konzeption, Umsetzung, Betrieb, Aufrechterhaltung und Verbesserung.', true),
(189, 'Idee, Entwurf, Prototyp, Serienproduktion.', false),
-- 190 SINGLE_CHOICE
(190, 'Risikomanagement, Notfallmanagement, Sensibilisierung der Mitarbeiter.', true),
(190, 'Nur Risikomanagement.', false),
(190, 'Nur Notfallmanagement.', false),
(190, 'Nur Sensibilisierung der Mitarbeiter.', false),
(190, 'Nur die IT-Budgetplanung.', false),
-- 191 SINGLE_CHOICE
(191, 'Anforderungen an die physische Sicherheit von Rechenzentren.', false),
(191, 'Regeln für die Programmierung sicherer Software.', false),
(191, 'Vorschriften für den Datenschutz in Europa.', false),
(191, 'Anforderungen an ein Informationssicherheits-Managementsystem (ISMS).', true),
(191, 'Kriterien für die Vergabe von Umweltzeichen.', false),
-- 192 SINGLE_CHOICE
(192, 'Wettbewerbsvorteil, Vertrauensbildung, Risikobehandlung.', true),
(192, 'Nur Wettbewerbsvorteil.', false),
(192, 'Nur Vertrauensbildung.', false),
(192, 'Nur Risikobehandlung.', false),
(192, 'Keine Vorteile.', false),
-- 193 SINGLE_CHOICE
(193, 'Die Verpackung gefällt nicht.', false),
(193, 'Der Lieferant war unfreundlich.', false),
(193, 'Man hat es sich anders überlegt.', false),
(193, 'Falsche Ware, beschädigte Ware, falsche Menge, Lieferverzug.', true),
(193, 'Die Rechnung wurde bereits bezahlt.', false),
-- 194 SINGLE_CHOICE
(194, 'Die Weiterleitung eines Problems an eine höhere Support-Ebene.', true),
(194, 'Die erste Kontaktaufnahme.', false),
(194, 'Die Lösung des Problems.', false),
(194, 'Die Dokumentation des Problems.', false),
(194, 'Die Bezahlung des Supports.', false),
-- 195 SINGLE_CHOICE
(195, 'Eine Liste der erlaubten Software im Unternehmen.', false),
(195, 'Ein Protokoll über einen Sicherheitsvorfall.', false),
(195, 'Ein Handbuch für die IT-Abteilung.', false),
(195, 'Ein Vertrag, der die Qualität, Verfügbarkeit und Reaktionszeiten einer Dienstleistung festlegt.', true),
(195, 'Ein Formular zur Beantragung von neuem IT-Equipment.', false),
-- 196 SINGLE_CHOICE
(196, 'Vertragsparteien, Kaufgegenstand, Kaufpreis, Liefer- und Zahlungsbedingungen.', true),
(196, 'Nur die Vertragsparteien.', false),
(196, 'Nur der Kaufgegenstand.', false),
(196, 'Nur der Kaufpreis.', false),
(196, 'Nur die Lieferbedingungen.', false),
-- 197 SINGLE_CHOICE
(197, '1st: E-Mail, 2nd: Telefon, 3rd: Vor Ort.', false),
(197, '1st: Junior, 2nd: Senior, 3rd: Chef.', false),
(197, 'Es gibt keinen Unterschied zwischen den Leveln.', false),
(197, '1st: Annahme. 2nd: Komplexe Probleme. 3rd: Experten/Hersteller.', true),
(197, '1st: Hardware, 2nd: Software, 3rd: Netzwerk.', false),
-- 198 MULTIPLE_CHOICE
(198, 'Leistungsumfang, Abnahmekriterien, Nutzungsrechte, Vergütung.', true),
(198, 'Die Namen der Entwickler', false),
(198, 'Abnahmekriterien', false),
(198, 'Nutzungsrechte (Lizenzen)', false),
(198, 'Vergütung', false),
-- 199 SINGLE_CHOICE
(199, 'Leistungsbeschreibung, SLAs, Laufzeit, Vergütung.', true),
(199, 'Nur die Leistungsbeschreibung.', false),
(199, 'Nur die SLAs.', false),
(199, 'Nur die Laufzeit.', false),
(199, 'Nur die Vergütung.', false),
-- 200 SINGLE_CHOICE
(200, 'Drucker 24/7 laufen lassen.', false),
(200, 'Alle E-Mails ausdrucken.', false),
(200, 'Serverräume auf 18 Grad kühlen.', false),
(200, 'Green IT: Virtualisierung, energieeffiziente Hardware, Recycling.', true),
(200, 'Hardware alle 6 Monate austauschen.', false),
-- 201 SINGLE_CHOICE
(201, 'Gewinnmaximierung, Umsatzsteigerung, Kostensenkung.', true),
(201, 'Nur Gewinnmaximierung.', false),
(201, 'Nur Umsatzsteigerung.', false),
(201, 'Nur Kostensenkung.', false),
(201, 'Kundenzufriedenheit.', false),
-- 202 SINGLE_CHOICE
(202, 'SaaS ist am teuersten, IaaS am günstigsten.', false),
(202, 'PaaS ist nur für Webhosting.', false),
(202, 'Alle drei Begriffe bedeuten dasselbe.', false),
(202, 'IaaS ist eine Software, SaaS eine Hardware.', false),
(202, 'IaaS: Infrastruktur. PaaS: Plattform. SaaS: Software.', true),
-- 203 SINGLE_CHOICE
(203, 'Eine grafische Darstellung der Aufbauorganisation.', true),
(203, 'Eine Darstellung der Ablauforganisation.', false),
(203, 'Ein Projektplan.', false),
(203, 'Ein Netzwerkdiagramm.', false),
(203, 'Eine Liste der Mitarbeiter.', false),
-- 204 SINGLE_CHOICE
(204, 'Die statische, hierarchische Gliederung eines Unternehmens.', true),
(204, 'Der dynamische Prozess der Leistungserstellung.', false),
(204, 'Der Lageplan der Büros.', false),
(204, 'Der Projektplan.', false),
(204, 'Die Urlaubsplanung.', false),
-- 205 SINGLE_CHOICE
(205, 'Ein Mitarbeiter erhält Anweisungen von mehreren Vorgesetzten.', true),
(205, 'Ein Mitarbeiter hat nur einen Vorgesetzten.', false),
(205, 'Ein Mitarbeiter hat keine Vorgesetzten.', false),
(205, 'Ein Mitarbeiter hat nur indirekte Vorgesetzte.', false),
(205, 'Ein Mitarbeiter hat nur fachliche Vorgesetzte.', false),
-- 206 SINGLE_CHOICE
(206, 'Die Abteilung des Geschäftsführers.', false),
(206, 'Eine Abteilung mit besonderer Entscheidungsgewalt.', false),
(206, 'Die unterste Ebene in der Hierarchie.', false),
(206, 'Eine beratende und unterstützende Einheit ohne Weisungsbefugnis.', true),
(206, 'Der Betriebsrat.', false),
-- 207 SINGLE_CHOICE
(207, 'Einliniensystem, ergänzt durch Stabsstellen.', true),
(207, 'Nur ein Einliniensystem.', false),
(207, 'Nur Stabsstellen.', false),
(207, 'Ein Mehrliniensystem.', false),
(207, 'Eine Matrixorganisation.', false),
-- 208 SINGLE_CHOICE
(208, 'Mitarbeiter haben zwei Vorgesetzte (funktional, disziplinarisch).', true),
(208, 'Eine Organisation ohne Vorgesetzte.', false),
(208, 'Eine sehr strenge, hierarchische Organisation.', false),
(208, 'Eine andere Bezeichnung für ein Einliniensystem.', false),
(208, 'Eine Organisation, die nur aus Projektteams besteht.', false),
-- 209 SINGLE_CHOICE
(209, 'i.V.: in Vollmacht, i.A.: im Auftrag, ppa.: per Prokura.', true),
(209, 'i.V.: in Vertretung, i.A.: auf Anfrage, ppa.: per Post.', false),
(209, 'i.V.: in Verantwortung, i.A.: auf Abruf, ppa.: per Post.', false),
(209, 'i.V.: in Vorauskasse, i.A.: auf Anweisung, ppa.: per Post.', false),
(209, 'i.V.: in Verzug, i.A.: auf Anraten, ppa.: per Post.', false),
-- 210 SINGLE_CHOICE
(210, 'Eine einmalige Vollmacht für ein bestimmtes Geschäft.', false),
(210, 'Die Erlaubnis, das Firmengelände zu betreten.', false),
(210, 'Die Befugnis, Mitarbeiter einzustellen.', false),
(210, 'Eine umfassende, gesetzlich definierte Vertretungsmacht.', true),
(210, 'Ein anderer Begriff für den Geschäftsführer.', false),
-- 211 SINGLE_CHOICE
(211, 'Jeder Geschäftsvorfall wird auf zwei Konten (Soll und Haben) gebucht.', true),
(211, 'Nur ein Konto pro Geschäftsvorfall.', false),
(211, 'Nur Soll-Buchungen.', false),
(211, 'Nur Haben-Buchungen.', false),
(211, 'Die Buchungen sind zufällig.', false),
-- 212 SINGLE_CHOICE
(212, 'Fortbildung ist länger als eine Umschulung.', false),
(212, 'Umschulung ist eine Art der Fortbildung.', false),
(212, 'Es gibt keinen Unterschied.', false),
(212, 'Fortbildung: Anpassung im Beruf. Umschulung: Erlernen eines neuen Berufs.', true),
(212, 'Fortbildung wird vom Staat bezahlt, Umschulung nicht.', false),
-- 213 SINGLE_CHOICE
(213, 'Maßnahmen zur Erweiterung beruflicher Kenntnisse.', true),
(213, 'Nur Maßnahmen zur Anpassung im Beruf.', false),
(213, 'Nur Maßnahmen zum Erlernen eines neuen Berufs.', false),
(213, 'Maßnahmen zur Reduzierung von Arbeitszeit.', false),
(213, 'Maßnahmen zur Erhöhung des Gehalts.', false),
-- 214 MULTIPLE_CHOICE
(214, 'Manuelle Tests durch den Entwickler', false),
(214, 'Unit-Test, Integrationstest, Systemtest, Akzeptanztest.', true),
(214, 'Integrationstest', false),
(214, 'Systemtest', false),
(214, 'Akzeptanztest', false),
-- 215 SINGLE_CHOICE
(215, 'White-Box-Tests sind einfacher als Black-Box-Tests.', false),
(215, 'Black-Box-Tests finden Fehler im Code, White-Box-Tests Fehler im Design.', false),
(215, 'Beide Testarten sind identisch.', false),
(215, 'Black-Box: Test ohne Kenntnis der Interna. White-Box: Test mit Kenntnis der Interna.', true),
(215, 'Nur White-Box-Tests können automatisiert werden.', false),
-- 216 SINGLE_CHOICE
(216, 'Ökologische, ökonomische und soziale Verantwortung.', true),
(216, 'Nur ökologische Verantwortung.', false),
(216, 'Nur ökonomische Verantwortung.', false),
(216, 'Nur soziale Verantwortung.', false),
(216, 'Nur die Einhaltung von Umweltgesetzen.', false),
-- 217 SINGLE_CHOICE
(217, 'Ein Protokoll über Fehler in der Software.', false),
(217, 'Eine Liste der offenen Aufgaben.', false),
(217, 'Die Rechnung für das Projekt.', false),
(217, 'Ein Dokument, das die Abnahme eines Projekts oder einer Leistung durch den Auftraggeber festhält.', true),
(217, 'Ein Handbuch für den Benutzer.', false),
-- 218 SINGLE_CHOICE
(218, 'Nur die Abnahme.', false),
(218, 'Nur die Rechnungsstellung.', false),
(218, 'Nur die Archivierung.', false),
(218, 'Abnahme, Rechnungsstellung, Archivierung.', true),
(218, 'Keine weiteren Schritte notwendig.', false),
-- 219 SINGLE_CHOICE
(219, 'Nur persönliche Einweisung vor Ort.', false),
(219, 'Nur per E-Mail.', false),
(219, 'Gar nicht, der Kunde soll es selbst herausfinden.', false),
(219, 'Persönliche Einweisung, Handbuch, Schulung.', true),
(219, 'Durch einen Link zu einem YouTube-Video.', false),
-- 220 SINGLE_CHOICE
(220, 'Eine Mischung aus Präsenzveranstaltungen und E-Learning.', true),
(220, 'Nur Präsenzveranstaltungen.', false),
(220, 'Nur E-Learning.', false),
(220, 'Eine reine Online-Schulung.', false),
(220, 'Eine reine Präsenzschulung.', false),
-- 221 SINGLE_CHOICE
(221, 'Das Zurücksetzen eines Systems auf Werkseinstellungen.', false),
(221, 'Das Erstellen eines Backups.', false),
(221, 'Das Löschen von alten Daten.', false),
(221, 'Die geplante Einführung neuer Hard- oder Software.', true),
(221, 'Die Inventarisierung der IT-Ausstattung.', false),
-- 222 MULTIPLE_CHOICE
(222, 'Planung, Paketierung, Pilotphase, Verteilung.', true),
(222, 'Die Software einfach allen zur Verfügung stellen und hoffen, dass es klappt.', false),
(222, 'Paketierung', false),
(222, 'Pilotphase', false),
(222, 'Verteilung', false),
-- 223 SINGLE_CHOICE
(223, 'Nur Beschaffung.', false),
(223, 'Nur Konfiguration.', false),
(223, 'Nur Verteilung.', false),
(223, 'Nur Entsorgung.', false),
(223, 'Beschaffung, Konfiguration, Verteilung, Entsorgung.', true),
-- 224 SINGLE_CHOICE
(224, 'Leasing ist eine Form des Kaufs.', false),
(224, 'Miete und Leasing sind dasselbe.', false),
(224, 'Beim Kauf hat man keine Garantie.', false),
(224, 'Kauf: Eigentum. Miete: Kurzfristige Nutzung. Leasing: Langfristige Nutzung.', true),
(224, 'Leasing ist immer die billigste Option.', false),
-- 225 SINGLE_CHOICE
(225, 'Vorteil: Eigentum. Nachteil: Hohe Kapitalbindung.', true),
(225, 'Nur Vorteile.', false),
(225, 'Nur Nachteile.', false),
(225, 'Immer günstiger als Leasing.', false),
(225, 'Immer teurer als Leasing.', false),
-- 226 SINGLE_CHOICE
(226, 'Vorteil: Man kann die Hardware behalten. Nachteil: Hohe monatliche Kosten.', false),
(226, 'Vorteil: Günstiger als Kauf. Nachteil: Man muss die Hardware selbst reparieren.', false),
(226, 'Es gibt nur Vorteile.', false),
(226, 'Vorteil: Aktuelle Hardware, geringe Kapitalbindung. Nachteil: Kein Eigentum, oft teurer.', true),
(226, 'Es gibt nur Nachteile.', false),
-- 227 SINGLE_CHOICE
(227, 'Aufbauorganisation: Wer? (Struktur). Ablauforganisation: Wie? (Prozesse).', true),
(227, 'Beides ist dasselbe.', false),
(227, 'Aufbauorganisation ist dynamisch, Ablauforganisation ist statisch.', false),
(227, 'Aufbauorganisation ist für Prozesse, Ablauforganisation für Strukturen.', false),
(227, 'Nur Aufbauorganisation ist relevant.', false),
-- 228 SINGLE_CHOICE
(228, 'Ein Diagramm zur Darstellung der Unternehmenshierarchie.', false),
(228, 'Ein Netzwerkdiagramm.', false),
(228, 'Ein Diagramm zur Darstellung von Datenbankbeziehungen.', false),
(228, 'Ein Balkendiagramm zur Darstellung eines Projektzeitplans.', true),
(228, 'Ein Kuchendiagramm zur Budgetaufteilung.', false),
-- 229 SINGLE_CHOICE
(229, 'Planung, Steuerung, Kontrolle, Abschluss von Projekten.', true),
(229, 'Nur Planung.', false),
(229, 'Nur Steuerung.', false),
(229, 'Nur Kontrolle.', false),
(229, 'Nur Abschluss.', false),
-- 230 SINGLE_CHOICE
(230, 'Die Zielkonflikte zwischen Zeit, Kosten und Qualität (Leistungsumfang).', true),
(230, 'Die drei wichtigsten Projektphasen.', false),
(230, 'Die drei Hauptkostenfaktoren.', false),
(230, 'Die drei wichtigsten Projektziele.', false),
(230, 'Die drei Säulen der Nachhaltigkeit.', false);

-- Zuordnung der Karten zu den Sets
INSERT INTO flashcard_set_mapping (flashcard_id, set_id) VALUES
(1, 2), (1, 23),
(2, 2), (2, 23),
(3, 2), (3, 23),
(4, 2), (4, 23),
(5, 2), (5, 23),
(6, 2), (6, 23),
(7, 2), (7, 23),
(8, 2), (8, 23),
(9, 2), (9, 23),
(10, 2), (10, 23),
(11, 2), (11, 24),
(12, 2), (12, 23),
(13, 2), (13, 24),
(14, 2), (14, 24),
(15, 2), (15, 24),
(16, 2), (16, 24),
(17, 2), (17, 24),
(18, 2), (18, 25),
(19, 2), (19, 23),
(20, 2), (20, 24),
(21, 2), (21, 24),
(22, 2), (22, 23),
(23, 2), (23, 25),
(24, 2), (24, 25),
(25, 2), (25, 25),
(26, 2), (26, 25),
(27, 2), (27, 25),
(28, 2), (28, 25),
(29, 2), (29, 25),
(30, 2), (30, 25),
(31, 2), (31, 25),
(32, 2), (32, 25),
(33, 2), (33, 25),
(34, 2), (34, 25),
(35, 2), (35, 25),
(36, 2), (36, 25),
(37, 2), (37, 25),
(38, 2), (38, 25),
(39, 2), (39, 25),
(40, 2), (40, 25),
(41, 2), (41, 25),
(42, 2), (42, 25),
(43, 2), (43, 25),
(44, 2), (44, 25),
(45, 2), (45, 25),
(46, 2), (46, 25),
(47, 2), (47, 25),
(48, 2), (48, 25),
(49, 2), (49, 25),
(50, 2), (50, 25),
(51, 2), (51, 25),
(52, 2), (52, 25),
(53, 2), (53, 25),
(54, 2), (54, 25),
(55, 2), (55, 25),
(56, 2), (56, 25),
(57, 2), (57, 25),
(58, 2), (58, 25),
(59, 2), (59, 25),
(60, 2), (60, 25),
(61, 2), (61, 25),
(62, 2), (62, 25),
(63, 2), (63, 25),
(64, 2), (64, 25),
(65, 2), (65, 25),
(66, 2), (66, 25),
(67, 2), (67, 25),
(68, 2), (68, 25),
(69, 2), (69, 25),
(70, 2), (70, 25),
(71, 2), (71, 25),
(72, 2), (72, 25),
(73, 2), (73, 25),
(74, 2), (74, 25),
(75, 2), (75, 25),
(76, 2), (76, 25),
(77, 2), (77, 25),
(78, 2), (78, 25),
(79, 2), (79, 25),
(80, 2), (80, 25),
(81, 2), (81, 25),
(82, 2), (82, 25),
(83, 2), (83, 25),
(84, 2), (84, 25),
(85, 2), (85, 23),
(86, 2), (86, 23),
(87, 2), (87, 23),
(88, 2), (88, 23),
(89, 2), (89, 25),
(90, 2), (90, 25),
(91, 2), (91, 25),
(92, 2), (92, 23),
(93, 2), (93, 25),
(94, 2), (94, 25),
(95, 2), (95, 25),
(96, 2), (96, 25),
(97, 2), (97, 25),
(98, 2), (98, 26),
(99, 2), (99, 25),
(100, 2), (100, 23),
(101, 2), (101, 23),
(102, 2), (102, 23),
(103, 2), (103, 23),
(104, 2), (104, 25),
(105, 2), (105, 25),
(106, 2), (106, 25),
(107, 2), (107, 26),
(108, 2), (108, 25),
(109, 2), (109, 25),
(110, 2), (110, 25),
(111, 2), (111, 23),
(112, 2), (112, 23),
(113, 2), (113, 23),
(114, 2), (114, 25),
(115, 2), (115, 25),
(116, 2), (116, 25),
(117, 2), (117, 25),
(118, 2), (118, 25),
(119, 2), (119, 25),
(120, 2), (120, 25),
(121, 2), (121, 26),
(122, 2), (122, 26),
(123, 2), (123, 26),
(124, 2), (124, 26),
(125, 2), (125, 26),
(126, 2), (126, 26),
(127, 2), (127, 26),
(128, 2), (128, 26),
(129, 2), (129, 26),
(130, 2), (130, 28),
(131, 2), (131, 28),
(132, 2), (132, 28),
(133, 2), (133, 28),
(134, 2), (134, 28),
(135, 2), (135, 28),
(136, 2), (136, 28),
(137, 2), (137, 28),
(138, 2), (138, 26),
(139, 2), (139, 25),
(140, 2), (140, 25),
(141, 2), (141, 25),
(142, 2), (142, 26),
(143, 2), (143, 26),
(144, 2), (144, 26),
(145, 2), (145, 26),
(146, 2), (146, 26),
(147, 2), (147, 26),
(148, 2), (148, 27),
(149, 2), (149, 27),
(150, 2), (150, 27),
(151, 2), (151, 27),
(152, 2), (152, 27),
(153, 2), (153, 27),
(154, 2), (154, 27),
(155, 2), (155, 27),
(156, 2), (156, 27),
(157, 2), (157, 28),
(158, 2), (158, 28),
(159, 2), (159, 28),
(160, 2), (160, 28),
(161, 2), (161, 28),
(162, 2), (162, 28),
(163, 2), (163, 28),
(164, 2), (164, 28),
(165, 2), (165, 28),
(166, 2), (166, 28),
(167, 2), (167, 28),
(168, 2), (168, 28),
(169, 2), (169, 28),
(170, 2), (170, 28),
(171, 2), (171, 28),
(172, 2), (172, 28),
(173, 2), (173, 28),
(174, 2), (174, 28),
(175, 2), (175, 28),
(176, 2), (176, 28),
(177, 2), (177, 28),
(178, 2), (178, 28),
(179, 2), (179, 28),
(180, 2), (180, 28),
(181, 2), (181, 27),
(182, 2), (182, 23),
(183, 2), (183, 27),
(184, 2), (184, 27),
(185, 2), (185, 28),
(186, 2), (186, 28),
(187, 2), (187, 28),
(188, 2), (188, 28),
(189, 2), (189, 28),
(190, 2), (190, 28),
(191, 2), (191, 28),
(192, 2), (192, 28),
(193, 2), (193, 29),
(194, 2), (194, 29),
(195, 2), (195, 29),
(196, 2), (196, 29),
(197, 2), (197, 29),
(198, 2), (198, 29),
(199, 2), (199, 29),
(200, 2), (200, 29),
(201, 2), (201, 29),
(202, 2), (202, 29),
(203, 2), (203, 23),
(204, 2), (204, 23),
(205, 2), (205, 23),
(206, 2), (206, 23),
(207, 2), (207, 23),
(208, 2), (208, 23),
(209, 2), (209, 23),
(210, 2), (210, 23),
(211, 2), (211, 23),
(212, 2), (212, 23),
(213, 2), (213, 23),
(214, 2), (214, 26),
(215, 2), (215, 26),
(216, 2), (216, 26),
(217, 2), (217, 29),
(218, 2), (218, 29),
(219, 2), (219, 29),
(220, 2), (220, 29),
(221, 2), (221, 29),
(222, 2), (222, 29),
(223, 2), (223, 29),
(224, 2), (224, 29),
(225, 2), (225, 29),
(226, 2), (226, 29),
(227, 2), (227, 23),
(228, 2), (228, 23),
(229, 2), (229, 23),
(230, 2), (230, 23);